/*INSERT DOS 151 POKEMONS*/
CALL sp_insert_pokemon ('Bulbasaur', 'Por algum tempo após seu nascimento, ele utiliza os nutrientes que estão contidos na semente em seu dorso para crescer.');
CALL sp_insert_pokemon ('Ivysaur', 'Quanto mais luz solar Ivysaur toma banho, mais força surge dentro dele, permitindo que o botão em suas costas cresça.');
CALL sp_insert_pokemon ('Venusaur', 'Enquanto se aquece ao sol, pode converter a luz em energia. Como resultado, é mais potente no verão.');
CALL sp_insert_pokemon('Charmander', 'A chama em sua cauda mostra a força de sua força vital. Se Charmander estiver fraco, a chama também queimará fracamente.');
CALL sp_insert_pokemon('Charmeleon', 'Quando ele balança sua cauda em chamas, a temperatura ao seu redor aumenta cada vez mais, atormentando seus oponentes.');
CALL sp_insert_pokemon('Charizard', 'Se Charizard ficar realmente irritado, a chama na ponta de sua cauda queima em um tom azul claro.');
CALL sp_insert_pokemon('Squirtle', 'Após o nascimento, suas costas incha e endurece formando uma concha. Ele espalha uma espuma potente pela boca.');
CALL sp_insert_pokemon('Wartortle', 'A cauda longa e peluda de Wartortle é um símbolo de longevidade, por isso este Pokémon é bastante popular entre os idosos.');
CALL sp_insert_pokemon('Blastoise', 'Ele aumenta deliberadamente o peso do corpo para poder suportar o recuo dos jatos de água que dispara.');
CALL sp_insert_pokemon('Caterpie', 'Para proteção, ele libera um fedor horrível da antena em sua cabeça para afastar os inimigos.');
CALL sp_insert_pokemon('Metapod', 'Está esperando o momento de evoluir. Nesta fase, ele só pode endurecer, por isso permanece imóvel para evitar ataques.');
CALL sp_insert_pokemon('Butterfree', 'Ele adora o néctar das flores e pode localizar manchas de flores que contenham até mesmo pequenas quantidades de pólen.');
CALL sp_insert_pokemon('Weedle', 'Cuidado com o ferrão afiado em sua cabeça. Esconde-se na grama e nos arbustos onde come folhas.');
CALL sp_insert_pokemon('Kakuna', 'Capaz de se mover apenas ligeiramente. Quando ameaçado, pode esticar o ferrão e envenenar o inimigo.');
CALL sp_insert_pokemon('Beedrill', 'Possui três ferrões venenosos nas patas dianteiras e na cauda. Eles são usados ​​para atacar repetidamente o inimigo.');
CALL sp_insert_pokemon('Pidgey', 'Muito dócil. Se for atacado, muitas vezes levanta areia para se proteger, em vez de revidar.');
CALL sp_insert_pokemon('Pidgeotto', 'Este Pokémon está cheio de vitalidade. Ele voa constantemente pelo seu grande território em busca de presas.');
CALL sp_insert_pokemon('Pidgeot', 'Este Pokémon voa na velocidade Mach 2 em busca de presas. Suas grandes garras são temidas como armas malignas.');
CALL sp_insert_pokemon('Rattata', 'Mastigará qualquer coisa com suas presas. Se você vir um, pode ter certeza de que mais 40 vivem na área.');
CALL sp_insert_pokemon('Raticate', 'Suas patas traseiras são palmadas. Eles agem como nadadeiras, para que possam nadar em rios e caçar presas.');
CALL sp_insert_pokemon('Spearow', 'Inepto em voar alto. No entanto, pode voar muito rápido para proteger o seu território.');
CALL sp_insert_pokemon('Fearow', 'Um Pokémon que remonta a muitos anos. Se sentir perigo, ele voa alto e para longe, instantaneamente.');
CALL sp_insert_pokemon('Ekans', 'Ele pode soltar livremente sua mandíbula para engolir presas grandes inteiras. No entanto, pode ficar muito pesado para ser movido.');
CALL sp_insert_pokemon('Arbok', 'O padrão em sua barriga parece ser um rosto assustador. Inimigos fracos fugirão apenas ao ver o padrão.');
CALL sp_insert_pokemon('Pikachu', 'Quando está irritado, descarrega imediatamente a energia armazenada nas bolsas em suas bochechas.');
CALL sp_insert_pokemon('Raichu', 'Sua cauda descarrega eletricidade no solo, protegendo-o de choques.');
CALL sp_insert_pokemon('Sandshrew', 'Ele cava tocas profundas para viver. Quando em perigo, enrola o corpo para resistir aos ataques.');
CALL sp_insert_pokemon('Sandslash', 'Ele é adepto de atacar com os espinhos nas costas e suas garras afiadas enquanto corre rapidamente.');
CALL sp_insert_pokemon('Nidoran♀', 'As fêmeas são mais sensíveis aos cheiros do que os machos. Enquanto procuram alimentos, eles usam seus bigodes para verificar a direção do vento e ficar na direção do vento em relação aos predadores.');
CALL sp_insert_pokemon('Nidorina', 'O chifre em sua cabeça atrofiou. Acredita-se que isso aconteça para que os filhos de Nidorina não sejam cutucados enquanto a mãe os alimenta.');
CALL sp_insert_pokemon('Nidoqueen', 'Nidoqueen é melhor na defesa do que no ataque. Com escamas como armaduras, este Pokémon protegerá seus filhos de qualquer tipo de ataque.');
CALL sp_insert_pokemon('Nidoran♂', 'O chifre na testa de um Nidoran masculino contém um veneno poderoso. Este é um Pokémon muito cauteloso, sempre esticando as orelhas grandes.');
CALL sp_insert_pokemon('Nidorino', 'Com um chifre mais duro que o diamante, este Pokémon despedaça pedras enquanto procura uma pedra da lua.');
CALL sp_insert_pokemon('Nidoking', 'Quando fica furioso, é impossível controlar. Mas na presença de uma Nidoqueen com quem convive há muito tempo, Nidoking se acalma.');
CALL sp_insert_pokemon('Clefairy', 'Nas noites de lua cheia, Clefairy se reúne em todos os lugares e dança. Tomar banho ao luar os faz flutuar.');
CALL sp_insert_pokemon('Clefable', 'Dizem que vivem em montanhas remotas e tranquilas, esse tipo de fada tem uma forte aversão a ser vista.');
CALL sp_insert_pokemon('Vulpix', 'Se for atacado por um inimigo mais forte que ele, ele finge estar ferido para enganar o inimigo e foge.');
CALL sp_insert_pokemon('Ninetales', 'Algumas lendas afirmam que cada uma de suas nove caudas tem seu próprio tipo de poder místico especial.');
CALL sp_insert_pokemon('Jigglypuff', 'Quando seus enormes olhos tremem, ele canta uma melodia misteriosamente reconfortante que acalma seus inimigos.');
CALL sp_insert_pokemon('Wigglytuff', 'Tem uma pelagem muito fina. Tome cuidado para não deixá-lo com raiva, ou ele pode inflar continuamente e bater com força.');
CALL sp_insert_pokemon('Zubat', 'Ele emite ondas ultrassônicas de sua boca para verificar o que está ao seu redor. Mesmo em cavernas estreitas, Zubat voa com habilidade.');
CALL sp_insert_pokemon('Golbat', 'Ele adora beber o sangue de outras criaturas. Dizem que se encontrar outros de sua espécie passando fome, às vezes ele compartilha o sangue que reuniu.');
CALL sp_insert_pokemon('Oddish', 'Seu nome científico é Oddium vagueus. Diz-se que ele percorre distâncias de até 300 metros quando a noite cai, caminhando sobre suas duas raízes.');
CALL sp_insert_pokemon('Gloom', 'O fluido que escorre da boca não é baba. É um néctar usado para atrair presas.');
CALL sp_insert_pokemon('Vileplume', 'O botão floresce com um estrondo. Em seguida, ele começa a espalhar pólen alergênico e venenoso.');
CALL sp_insert_pokemon('Paras', 'Cria tocas subterrâneas para roer raízes de árvores. Os cogumelos nas costas absorvem a maior parte da nutrição.');
CALL sp_insert_pokemon('Parasect', 'O hospedeiro do inseto fica sem energia pelo cogumelo em suas costas. O cogumelo parece fazer todo o pensamento.');
CALL sp_insert_pokemon('Venonat', 'O veneno escorre por todo o seu corpo. Ele captura pequenos insetos à noite que são atraídos pela luz.');
CALL sp_insert_pokemon('Venomoth', 'As asas são cobertas por escamas semelhantes a poeira. Cada vez que bate as asas, libera poeira altamente tóxica.');
CALL sp_insert_pokemon('Diglett', 'Vive cerca de um metro abaixo do solo, onde se alimenta de raízes de plantas. Às vezes aparece acima do solo.');
CALL sp_insert_pokemon('Dugtrio', 'Suas três cabeças balançam separadamente para cima e para baixo para soltar o solo próximo, facilitando a escavação.');
CALL sp_insert_pokemon('Meowth', 'Tudo o que faz é dormir durante o dia. À noite, patrulha seu território com os olhos brilhantes.');
CALL sp_insert_pokemon('Persian', 'Embora seu pelo tenha muitos admiradores, é difícil criá-lo como animal de estimação por causa de sua maldade inconstante.');
CALL sp_insert_pokemon('Psyduck', 'É constantemente assolado por uma dor de cabeça. Quando a dor de cabeça fica intensa, ela começa a usar poderes misteriosos.');
CALL sp_insert_pokemon('Golduck', 'Quando ele nada a toda velocidade usando seus membros longos e palmados, sua testa de alguma forma começa a brilhar.');
CALL sp_insert_pokemon('Mankey', 'Vive em grupos nas copas das árvores. Se perder de vista o seu grupo, ficará furioso com a sua solidão.');
CALL sp_insert_pokemon('Primeape', 'Fica extremamente furioso se sentir alguém olhando para ele. Ele persegue qualquer um que encontre seu brilho.');
CALL sp_insert_pokemon('Growlithe', 'Tem uma natureza corajosa e confiável. Ele enfrenta destemidamente inimigos maiores e mais fortes.');
CALL sp_insert_pokemon('Arcanine', 'Um antigo pergaminho ilustrado mostra que as pessoas ficavam cativadas por seu movimento enquanto ele percorria as pradarias.');
CALL sp_insert_pokemon('Poliwag', 'O redemoinho em sua barriga mostra seu interior aparecendo através da pele. Aparece mais claramente depois que Poliwag come.');
CALL sp_insert_pokemon('Poliwhirl', 'Suas duas pernas são bem desenvolvidas. Embora possa viver no solo, prefere viver na água.');
CALL sp_insert_pokemon('Poliwrath', 'Embora seja hábil em um estilo de natação dinâmico que utiliza todos os seus músculos, por algum motivo vive em terra firme.');
CALL sp_insert_pokemon('Abra', 'Este Pokémon usa seus poderes psíquicos enquanto dorme. O conteúdo dos sonhos de Abra afeta os poderes que o Pokémon exerce.');
CALL sp_insert_pokemon('Kadabra', 'Usando seu poder psíquico, Kadabra levita enquanto dorme. Ele usa sua cauda elástica como travesseiro.');
CALL sp_insert_pokemon('Alakazam', 'Tem um nível de inteligência incrivelmente alto. Alguns dizem que Alakazam se lembra de tudo o que acontece com ele, desde o nascimento até a morte.');
CALL sp_insert_pokemon('Machop', 'Todo o seu corpo é composto por músculos. Mesmo sendo do tamanho de uma criança humana, pode arremessar 100 adultos.');
CALL sp_insert_pokemon('Machoke', 'Seu corpo musculoso é tão poderoso que ele deve usar um cinto economizador de energia para poder regular seus movimentos.');
CALL sp_insert_pokemon('Machamp', 'Ele soca com seus quatro braços em uma velocidade estonteante. Pode lançar 1.000 socos em dois segundos.');
CALL sp_insert_pokemon('Bellsprout', 'Não importa o que Bellsprout esteja fazendo, se detectar movimento próximo, ele reagirá imediatamente estendendo a mão com suas vinhas finas.');
CALL sp_insert_pokemon('Weepinbell', 'Embora esteja cheio de ácido, não derrete porque também exala um fluido protetor.');
CALL sp_insert_pokemon('Victreebel', 'Ele atrai a presa para a boca com um aroma de néctar. A presa indefesa é derretida com um líquido dissolvente.');
CALL sp_insert_pokemon('Tentacool', 'Quando a maré baixa, Tentacool desidratado pode ser encontrado deixado para trás na costa.');
CALL sp_insert_pokemon('Tentacruel', 'Nas raras ocasiões em que ocorrem grandes surtos de Tentacruel, todos os Pokémon peixes desaparecem do mar circundante.');
CALL sp_insert_pokemon('Geodude', 'Em repouso, parece uma pedra. Pisá-lo descuidadamente fará com que ele balance os punhos com raiva.');
CALL sp_insert_pokemon('Graveler', 'Um Caminhante lento, ele rola para se mover. Ele não presta atenção a nenhum objeto que esteja em seu caminho.');
CALL sp_insert_pokemon('Golem', 'Está envolto em uma casca dura que é tão robusta quanto placas de rocha. Ele troca de pele uma vez por ano para crescer.');
CALL sp_insert_pokemon('Ponyta', 'Cerca de uma hora após o nascimento, a crina e a cauda flamejantes de Ponyta crescem, dando ao Pokémon uma aparência impressionante.');
CALL sp_insert_pokemon('Rapidash', 'Ele galopa a quase 150 mph. Com sua crina brilhando ferozmente, ele corre como se fosse uma flecha.');
CALL sp_insert_pokemon('Slowpoke', 'É incrivelmente lento e estúpido. Demora cinco segundos para sentir dor quando está sob ataque.');
CALL sp_insert_pokemon('Slowbro', 'Quando um Slowpoke foi caçar no mar, sua cauda foi mordida por um Shellder. Isso o fez evoluir para Slowbro');
CALL sp_insert_pokemon('Magnemite', 'As ondas eletromagnéticas emitidas pelas unidades nas laterais de sua cabeça expelem a antigravidade, o que lhe permite flutuar.');
CALL sp_insert_pokemon('Magneton', 'Três Magnemite estão ligados por uma forte força magnética. Dores de ouvido ocorrerão se você chegar muito perto.');
CALL sp_insert_pokemon('Farfetch’d', 'Não pode viver sem o talo que segura. É por isso que defende o talo dos atacantes com a sua vida.');
CALL sp_insert_pokemon('Doduo', 'Suas cabeças gêmeas têm exatamente os mesmos genes e lutam em perfeita sincronia entre si.');
CALL sp_insert_pokemon('Dodrio', 'Agora tem três corações e três conjuntos de pulmões. Embora não possa correr tão rápido quanto Doduo, Dodrio pode continuar correndo por longos períodos de tempo.');
CALL sp_insert_pokemon('Seel', 'A saliência na cabeça é muito dura. É usado para quebrar gelo espesso.');
CALL sp_insert_pokemon('Dewgong', 'Ele dorme nas águas rasas do oceano durante o dia e depois procura comida à noite, quando está mais frio.');
CALL sp_insert_pokemon('Grimer', 'Nascidos do lodo, esses Pokémon agora se reúnem em locais poluídos e aumentam as bactérias em seus corpos.');
CALL sp_insert_pokemon('Muk', 'Está densamente coberto com um lodo imundo e vil. É tão tóxico que até suas pegadas contêm veneno.');
CALL sp_insert_pokemon('Shellder', 'Está envolto em uma concha que é mais dura que o diamante. Por dentro, porém, é surpreendentemente macio.');
CALL sp_insert_pokemon('Cloyster', 'Cloyster que vive em mares com fortes correntes de maré desenvolvem pontas grandes e afiadas em suas conchas.');
CALL sp_insert_pokemon('Gastly', 'Ele envolve seu oponente em seu corpo gasoso, enfraquecendo lentamente sua presa ao envenená-la através da pele.');
CALL sp_insert_pokemon('Haunter', 'Ele gosta de se esconder no escuro e bater nos ombros com a mão gasosa. Seu toque causa estremecimentos sem fim.');
CALL sp_insert_pokemon('Gengar', 'Para roubar a vida do seu alvo, ele se esconde na sombra da presa e espera silenciosamente por uma oportunidade.');
CALL sp_insert_pokemon('Onix', 'À medida que escava o solo, absorve muitos objetos duros. É isso que torna seu corpo tão sólido.');
CALL sp_insert_pokemon('Drowzee', 'Ele se lembra de cada sonho que come. Raramente come os sonhos dos adultos porque os das crianças são muito mais saborosos.');
CALL sp_insert_pokemon('Hypno', 'Quando ele encara um inimigo, ele usa uma mistura de movimentos psíquicos, como Hipnose e Confusão.');
CALL sp_insert_pokemon('Krabby', 'Pode ser encontrado perto do mar. As pinças grandes voltam a crescer se forem arrancadas das órbitas.');
CALL sp_insert_pokemon('Kingler', 'A pinça maior tem força de 10.000 cavalos de potência. No entanto, é tão pesado que é difícil mirar.');
CALL sp_insert_pokemon('Voltorb', 'Ele rola para se mover. Se o solo for irregular, um solavanco repentino ao atingir uma colisão pode fazer com que ela exploda.');
CALL sp_insert_pokemon('Electrode', 'Quanto mais energia ele carrega, mais rápido fica. Mas isso também aumenta a probabilidade de explodir.');
CALL sp_insert_pokemon('Exeggcute', 'Se você tocar em uma das cabeças de Exeggcute, confundindo-a com um ovo, as outras cabeças irão rapidamente se reunir e atacar você em um enxame.');
CALL sp_insert_pokemon('Exeggutor', 'É chamada de Selva Ambulante. Cada uma das nozes tem um rosto e uma vontade própria.');
CALL sp_insert_pokemon('Cubone', 'Quando a memória de sua mãe falecida o leva às lágrimas, seus gritos ecoam tristemente dentro do crânio que ele usa na cabeça.');
CALL sp_insert_pokemon('Marowak', 'Este Pokémon superou sua tristeza para desenvolver um novo corpo robusto. Marowak enfrenta seus oponentes com bravura, usando um osso como arma.');
CALL sp_insert_pokemon('Hitmonlee', 'No exato momento em que acerta o chute no alvo, Hitmonlee endurece os músculos da sola do pé, maximizando a força do chute.');
CALL sp_insert_pokemon('Hitmonchan', 'Ele encurrala seus inimigos com socos combinados de ambos os lados e depois os finaliza com um único soco direto lançado a mais de 480 km/h.');
CALL sp_insert_pokemon('Lickitung', 'Se a saliva pegajosa deste Pokémon entrar em contato com você e você não limpá-la, uma coceira intensa se instalará.');
CALL sp_insert_pokemon('Koffing', 'O gás tóxico é mantido dentro de seu corpo fino em forma de balão, podendo causar explosões massivas.');
CALL sp_insert_pokemon('Weezing', 'O perfume de alta qualidade é feito usando seus gases venenosos internos, diluindo-os ao mais alto nível.');
CALL sp_insert_pokemon('Rhyhorn', 'Rhyhorn reivindica uma área com mais de seis milhas de raio como seu território. Aparentemente, ele se esquece de onde fica esse território durante a execução');
CALL sp_insert_pokemon('Rhydon', 'O chifre de um Rhydon é poderoso o suficiente para esmagar diamantes brutos. Esses Pokémon aprimoram seus chifres batendo-os um no outro.');
CALL sp_insert_pokemon('Chansey', 'Este gentil Pokémon põe ovos altamente nutritivos e os compartilha com Pokémon ou pessoas feridas.');
CALL sp_insert_pokemon('Tangela', 'Escondido sob um emaranhado de vinhas que cresce sem parar mesmo que as vinhas sejam arrancadas, a verdadeira aparência deste Pokémon permanece um mistério.');
CALL sp_insert_pokemon('Kangaskhan', 'Embora carregue seu bebê em uma bolsa na barriga, Kangaskhan é rápido. Intimida seus oponentes com golpes rápidos.');
CALL sp_insert_pokemon('Horsea', 'Se for atacado, mesmo por um grande inimigo, Horsea nada sem esforço para um local seguro, utilizando sua barbatana dorsal bem desenvolvida.');
CALL sp_insert_pokemon('Seadra', 'O macho cria os filhotes. Se for abordado enquanto cuida dos filhotes, usará seus espinhos tóxicos para afastar o intruso.');
CALL sp_insert_pokemon('Goldeen', 'Suas barbatanas dorsal, peitoral e caudal ondulam elegantemente na água. É por isso que é conhecido como Dançarino da Água.');
CALL sp_insert_pokemon('Seaking', 'No outono, seu corpo fica mais gorduroso ao se preparar para pedir um companheiro em casamento. Adquire lindas cores.');
CALL sp_insert_pokemon('Staryu', 'Se você visitar uma praia no final do verão, poderá ver grupos de Staryu iluminando-se em ritmo constante.');
CALL sp_insert_pokemon('Starmie', 'Este Pokémon possui um órgão conhecido como núcleo. O órgão brilha em sete cores quando Starmie libera seus potentes poderes psíquicos.');
CALL sp_insert_pokemon('Mr. Mime', 'É um especialista em pantomima que pode criar paredes invisíveis, mas sólidas, usando gestos de mímica.');
CALL sp_insert_pokemon('Scyther', 'Ele corta a grama com suas foices afiadas, movendo-se rápido demais para ser rastreado pelo olho humano.');
CALL sp_insert_pokemon('Jynx', 'Em certas partes de Galar, Jynx já foi temida e adorada como a Rainha do Gelo.');
CALL sp_insert_pokemon('Electabuzz', 'Seu corpo descarrega eletricidade constantemente. Chegar perto dele deixará seus cabelos em pé.');
CALL sp_insert_pokemon('Magmar', 'Encontrado perto da boca de um vulcão. A temperatura corporal deste respirador de fogo é de quase 2.200 graus Fahrenheit.');
CALL sp_insert_pokemon('Pinsir', 'Esses Pokémon julgam uns aos outros com base em pinças. Pinças mais grossas e impressionantes aumentam a popularidade entre o sexo oposto.');
CALL sp_insert_pokemon('Tauros', 'Quando atinge um inimigo, ele ataca furiosamente enquanto chicoteia seu corpo com suas longas caudas.');
CALL sp_insert_pokemon('Magikarp', 'Um Pokémon patético e pouco poderoso. Pode saltar alto em raras ocasiões, mas nunca mais de dois metros.');
CALL sp_insert_pokemon('Gyarados', 'Uma vez que aparece, ele fica furioso. Ele permanece enfurecido até destruir tudo ao seu redor.');
CALL sp_insert_pokemon('Lapras', 'Ele transporta pessoas através do mar em suas costas. Pode cantar um grito encantador se estiver de bom humor.');
CALL sp_insert_pokemon('Ditto', 'Sua capacidade de transformação é perfeita. No entanto, se for feito rir, não consegue manter o disfarce.');
CALL sp_insert_pokemon('Eevee', 'A sua capacidade de evoluir em muitas formas permite-lhe adaptar-se de forma suave e perfeita a qualquer ambiente.');
CALL sp_insert_pokemon('Vaporeon', 'Vive perto da água. Sua longa cauda é estriada por uma barbatana, que muitas vezes é confundida com a de uma sereia.');
CALL sp_insert_pokemon('Jolteon', 'Ele concentra as fracas cargas elétricas emitidas por suas células e lança relâmpagos perversos.');
CALL sp_insert_pokemon('Flareon', 'O ar inalado é transportado para o seu saco de chamas, aquecido e exalado como fogo que atinge mais de 3.000 graus Fahrenheit.');
CALL sp_insert_pokemon('Porygon', 'É um Pokémon artificial. Como não respira, as pessoas ficam entusiasmadas com o seu potencial de ser útil em qualquer ambient');
CALL sp_insert_pokemon('Omanyte', 'Como alguns Omanytes conseguem escapar após serem restaurados ou são soltos na natureza pelas pessoas, esta espécie está se tornando um problema.');
CALL sp_insert_pokemon('Omastar', 'Sobrecarregado por uma concha grande e pesada, Omastar não conseguia se mover muito rápido. Alguns dizem que foi extinto porque não conseguia pegar comida.');
CALL sp_insert_pokemon('Kabuto', 'Esta espécie está quase totalmente extinta. Kabuto muda a cada três dias, tornando suas conchas cada vez mais duras.');
CALL sp_insert_pokemon('Kabutops', 'Kabutops corta sua presa e suga os fluidos. As partes do corpo descartadas servem de alimento para outros Pokémon.');
CALL sp_insert_pokemon('Aerodactyl', 'Este é um Pokémon feroz dos tempos antigos. Aparentemente, mesmo a tecnologia moderna é incapaz de produzir um espécime perfeitamente restaurado.');
CALL sp_insert_pokemon('Snorlax', 'Este Pokémon guloso come constantemente, exceto quando está dormindo. Ele devora quase 900 quilos de comida por dia.');
CALL sp_insert_pokemon('Articuno', 'Este lendário Pokémon pássaro pode criar nevascas ao congelar a umidade do ar.');
CALL sp_insert_pokemon('Zapdos', 'Diz-se que este Pokémon lendário vive em nuvens de tempestade. Ele controla livremente os raios.');
CALL sp_insert_pokemon('Moltres', 'É um dos lendários Pokémon pássaros. Diz-se que seu aparecimento indica a chegada da primavera.');
CALL sp_insert_pokemon('Dratini', 'Ele perde muitas camadas de pele à medida que cresce. Durante esse processo, é protegido por uma rápida cachoeira.');
CALL sp_insert_pokemon('Dragonair', 'Dizem que se emitir uma aura de todo o corpo, o clima começará a mudar instantaneamente.');
CALL sp_insert_pokemon('Dragonite', 'Diz-se que em algum lugar do oceano existe uma ilha onde estes se reúnem. Só eles moram lá.');
CALL sp_insert_pokemon('Mewtwo', 'Seu DNA é quase igual ao de Mew. No entanto, seu tamanho e disposição são muito diferentes.');
CALL sp_insert_pokemon('Mew', 'Quando visto através de um microscópio, o cabelo curto, fino e delicado deste Pokémon pode ser visto.');

/*INSERT DA TABELA DE TIPOS*/
CALL sp_insert_tipo('Normal');
CALL sp_insert_tipo('Grama');
CALL sp_insert_tipo('Fogo');
CALL sp_insert_tipo('Água');
CALL sp_insert_tipo('Lutador');
CALL sp_insert_tipo('Voador');
CALL sp_insert_tipo('Venenoso');
CALL sp_insert_tipo('Terrestre');
CALL sp_insert_tipo('Rocha');
CALL sp_insert_tipo('Inseto');
CALL sp_insert_tipo('Fantasma');
CALL sp_insert_tipo('Elétrico');
CALL sp_insert_tipo('Psíquico');
CALL sp_insert_tipo('Gelo');
CALL sp_insert_tipo('Dragão');
CALL sp_insert_tipo('Noturno');
CALL sp_insert_tipo('Metal');
CALL sp_insert_tipo('Fada');

/*INSERT DA TABELA DE FRAQUEZAS*/
CALL sp_insert_fraqueza('Normal');
CALL sp_insert_fraqueza('Grama');
CALL sp_insert_fraqueza('Fogo');
CALL sp_insert_fraqueza('Água');
CALL sp_insert_fraqueza('Lutador');
CALL sp_insert_fraqueza('Voador');
CALL sp_insert_fraqueza('Venenoso');
CALL sp_insert_fraqueza('Terrestre');
CALL sp_insert_fraqueza('Rocha');
CALL sp_insert_fraqueza('Inseto');
CALL sp_insert_fraqueza('Fantasma');
CALL sp_insert_fraqueza('Elétrico');
CALL sp_insert_fraqueza('Psíquico');
CALL sp_insert_fraqueza('Gelo');
CALL sp_insert_fraqueza('Dragão');
CALL sp_insert_fraqueza('Noturno');
CALL sp_insert_fraqueza('Aço');
CALL sp_insert_fraqueza('Fada');

/*INSERT DA TABELA DOS POKEMONS*/
CALL sp_insert_evolucao('Ivysaur');
CALL sp_insert_evolucao('Venusaur');
CALL sp_insert_evolucao('Charmeleon');
CALL sp_insert_evolucao('Charizard');
CALL sp_insert_evolucao('Wartortle');
CALL sp_insert_evolucao('Blastoise');
CALL sp_insert_evolucao('Metapod');
CALL sp_insert_evolucao('Butterfree');
CALL sp_insert_evolucao('Kakuna');
CALL sp_insert_evolucao('Beedrill');
CALL sp_insert_evolucao('Pidgeotto');
CALL sp_insert_evolucao('Pidgeot');
CALL sp_insert_evolucao('Raticate');
CALL sp_insert_evolucao('Fearow');
CALL sp_insert_evolucao('Arbok');
CALL sp_insert_evolucao('Raichu');
CALL sp_insert_evolucao('Sandslash');
CALL sp_insert_evolucao('Nidorina');
CALL sp_insert_evolucao('Nidoqueen');
CALL sp_insert_evolucao('Nidorino');
CALL sp_insert_evolucao('Nidoking');
CALL sp_insert_evolucao('Clefable');
CALL sp_insert_evolucao('Ninetales');
CALL sp_insert_evolucao('Wigglytuff');
CALL sp_insert_evolucao('Golbat');
CALL sp_insert_evolucao('Gloom');
CALL sp_insert_evolucao('Vileplume');
CALL sp_insert_evolucao('Parasect');
CALL sp_insert_evolucao('Venomoth');
CALL sp_insert_evolucao('Dugtrio');
CALL sp_insert_evolucao('Persian');
CALL sp_insert_evolucao('Golduck');
CALL sp_insert_evolucao('Primeape');
CALL sp_insert_evolucao('Arcanine');
CALL sp_insert_evolucao('Poliwhirl');
CALL sp_insert_evolucao('Poliwrath');
CALL sp_insert_evolucao('Kadabra');
CALL sp_insert_evolucao('Alakazam');
CALL sp_insert_evolucao('Machoke');
CALL sp_insert_evolucao('Machamp');
CALL sp_insert_evolucao('Weepinbell');
CALL sp_insert_evolucao('Victreebel');
CALL sp_insert_evolucao('Tentacruel');
CALL sp_insert_evolucao('Graveler');
CALL sp_insert_evolucao('Golem');
CALL sp_insert_evolucao('Rapidash');
CALL sp_insert_evolucao('Slowbro');
CALL sp_insert_evolucao('Magneton');
CALL sp_insert_evolucao('Dodrio');
CALL sp_insert_evolucao('Dewgong');
CALL sp_insert_evolucao('Muk');
CALL sp_insert_evolucao('Cloyster');
CALL sp_insert_evolucao('Haunter');
CALL sp_insert_evolucao('Gengar');
CALL sp_insert_evolucao('Hypno');
CALL sp_insert_evolucao('Kingler');
CALL sp_insert_evolucao('Electrode');
CALL sp_insert_evolucao('Exeggutor');
CALL sp_insert_evolucao('Marowak');
CALL sp_insert_evolucao('Weezing');
CALL sp_insert_evolucao('Rhydon');
CALL sp_insert_evolucao('Seadra');
CALL sp_insert_evolucao('Seaking');
CALL sp_insert_evolucao('Starmie');
CALL sp_insert_evolucao('Gyarados');
CALL sp_insert_evolucao('Vaporeon');
CALL sp_insert_evolucao('Jolteon');
CALL sp_insert_evolucao('Flareon');
CALL sp_insert_evolucao('Omastar');
CALL sp_insert_evolucao('Kabutops');
CALL sp_insert_evolucao('Dragonair');
CALL sp_insert_evolucao('Dragonite');

/*INSERTS DA TABELA DE HABILIDADES*/
CALL sp_insert_habilidade('Overgrow', 'Aumenta os movimentos do tipo Grass quando o HP do Pokémon está baixo.');
CALL sp_insert_habilidade('Chlorophyll', 'Aumenta a estatística de velocidade do Pokémon sob a luz do sol.');
CALL sp_insert_habilidade('Blaze', 'Aumenta os movimentos do tipo Fire quando o HP do Pokémon está baixo.');
CALL sp_insert_habilidade('Solar Power', 'Aumenta o Sp. Estatística de ataque em tempo ensolarado, mas o HP diminui a cada turno.');
CALL sp_insert_habilidade('Torrent', 'Aumenta os movimentos do tipo Água quando o HP do Pokémon está baixo.');
CALL sp_insert_habilidade('Rain Dish', 'O Pokémon recupera HP gradualmente na chuva.');
CALL sp_insert_habilidade('Shield Dust', 'A poeira deste Pokémon bloqueia os efeitos adicionais dos ataques recebidos.');
CALL sp_insert_habilidade('Run Away', 'Permite uma fuga segura de Pokémon selvagens.');
CALL sp_insert_habilidade('Shed Skin', 'O Pokémon pode curar suas próprias condições de status trocando de pele.');
CALL sp_insert_habilidade('Compoundeyes', 'Os olhos compostos do Pokémon aumentam sua precisão.');
CALL sp_insert_habilidade('Tinted Lens', 'O Pokémon pode usar movimentos “não muito eficazes” para causar danos regulares.');
CALL sp_insert_habilidade('Swarm', 'Aumenta movimentos do tipo Inseto quando o HP do Pokémon está baixo.');
CALL sp_insert_habilidade('Sniper', 'Aumenta os movimentos se eles se tornarem acertos críticos ao atacar.');
CALL sp_insert_habilidade('Keen Eye', 'Olhos aguçados evitam que outros Pokémon diminuam a precisão deste Pokémon.');
CALL sp_insert_habilidade('Tangled Feet', 'Aumenta a evasão se o Pokémon estiver confuso.');
CALL sp_insert_habilidade('Big Pecks', 'Protege o Pokémon dos efeitos de redução de defesa.');
CALL sp_insert_habilidade('Guts', 'É tão corajoso que ter uma condição de status aumenta as estatísticas de ataque do Pokémon.');
CALL sp_insert_habilidade('Hustle', 'Aumenta a estatística de ataque, mas diminui a precisão.');
CALL sp_insert_habilidade('Intimidate', 'O Pokémon intimida os Pokémon adversários ao entrar na batalha, diminuindo suas estatísticas de ataque.');
CALL sp_insert_habilidade('Unnerve', 'Enerva os Pokémon oponentes e os impede de comer frutas.');
CALL sp_insert_habilidade('Static', 'O Pokémon está carregado de eletricidade estática, então o contato com ele pode causar paralisia.');
CALL sp_insert_habilidade('Lightning Rod', 'O Pokémon atrai todos os movimentos do tipo Elétrico. Em vez de ser atingido por golpes do tipo Elétrico, ele aumenta seu Sp. Atk.');
CALL sp_insert_habilidade('Sand Veil', 'Aumenta a evasão do Pokémon em uma tempestade de areia.');
CALL sp_insert_habilidade('Sand Rush', 'Aumenta a velocidade do Pokémon em uma tempestade de areia.');
CALL sp_insert_habilidade('Poison Point', 'O contato com o Pokémon pode envenenar o atacante.');
CALL sp_insert_habilidade('Rivalry', 'Torna-se competitivo e causa mais danos a Pokémon do mesmo sexo, mas causa menos danos a Pokémon do sexo oposto.');
CALL sp_insert_habilidade('Sheer Force', 'Remove efeitos adicionais para aumentar o poder dos movimentos ao atacar.');
CALL sp_insert_habilidade('Cute Charm', 'O contato com o Pokémon pode causar paixão.');
CALL sp_insert_habilidade('Magic Guard', 'O Pokémon só sofre danos de ataques.');
CALL sp_insert_habilidade('Friend Guard', 'Reduz o dano causado aos aliados.');
CALL sp_insert_habilidade('Unaware', 'Ao atacar, o Pokémon ignora as alterações nas estatísticas do Pokémon alvo.');
CALL sp_insert_habilidade('Flash Fire', 'Aumenta os movimentos do tipo Fogo do Pokémon se ele for atingido por um.');
CALL sp_insert_habilidade('Drought', 'Torna a luz do sol forte quando o Pokémon entra em batalha.');
CALL sp_insert_habilidade('Competitive', 'Aumenta o Sp. Estatística de ataque acentuadamente quando uma estatística é reduzida.');
CALL sp_insert_habilidade('Frisk', 'Quando entra em uma batalha, o Pokémon pode verificar o item segurado pelo Pokémon adversário.');
CALL sp_insert_habilidade('Inner Focus', 'O Pokémon está intensamente focado e isso o protege de vacilar.');
CALL sp_insert_habilidade('Infiltrator', 'Passa pela barreira, substituto e similares do Pokémon adversário e ataca.');
CALL sp_insert_habilidade('Stench', 'Ao liberar fedor ao atacar, este Pokémon pode fazer o alvo recuar.');
CALL sp_insert_habilidade('Effect Spore', 'O contato com o Pokémon pode causar veneno, sono ou paralisia ao atacante.');
CALL sp_insert_habilidade('Dry Skin', 'Restaura o HP na chuva ou quando atingido por golpes do tipo Água. Reduz o HP sob a luz do sol e aumenta o dano recebido de movimentos do tipo Fogo.');
CALL sp_insert_habilidade('Damp', 'Impede o uso de movimentos explosivos, como a Autodestruição, amortecendo o ambiente.');
CALL sp_insert_habilidade('Wonder Skin', 'Torna os movimentos de status mais propensos a falhar.');
CALL sp_insert_habilidade('Arena Trap', 'Impede que Pokémon adversários fujam');
CALL sp_insert_habilidade('Sand Force', 'Aumenta o poder dos movimentos do tipo Rock, Ground e Steel em uma tempestade de areia.');
CALL sp_insert_habilidade('Pickup', 'O Pokémon pode pegar o item que um Pokémon adversário usou durante uma batalha. Ele também pode pegar itens fora da batalha.');
CALL sp_insert_habilidade('Technician', 'Aumenta os movimentos mais fracos do Pokémon.');
CALL sp_insert_habilidade('Limber', 'Seu corpo flexível protege o Pokémon da paralisia.');
CALL sp_insert_habilidade('Cloud Nine', 'Elimina os efeitos do clima.');
CALL sp_insert_habilidade('Swift Swim', 'Aumenta a estatística de velocidade do Pokémon na chuva.');
CALL sp_insert_habilidade('Vital Spirit', 'O Pokémon está cheio de vitalidade e isso o impede de adormecer.');
CALL sp_insert_habilidade('Anger Point', 'O Pokémon fica irritado quando recebe um golpe crítico, e isso maximiza sua estatística de Ataque.');
CALL sp_insert_habilidade('Defiant', 'Aumenta drasticamente as estatísticas de ataque do Pokémon quando suas estatísticas são reduzidas.');
CALL sp_insert_habilidade('Justified', 'Ser atingido por um movimento do tipo Noturno aumenta a estatística de ataque do Pokémon, por justiça.');
CALL sp_insert_habilidade('Water Absorb', 'Restaura o HP se for atingido por um movimento do tipo Água, em vez de sofrer dano.');
CALL sp_insert_habilidade('Synchronize', 'O atacante receberá a mesma condição de status se infligir queimadura, veneno ou paralisia ao Pokémon.');
CALL sp_insert_habilidade('No Guard', 'O Pokémon emprega táticas sem guarda para garantir que os ataques recebidos e enviados sempre acertem.');
CALL sp_insert_habilidade('Steadfast', 'A determinação do Pokémon aumenta a estatística de velocidade cada vez que o Pokémon recua.');
CALL sp_insert_habilidade('Gluttony', 'Faz o Pokémon comer uma Berry segurada quando seu HP cai para metade ou menos, o que é mais cedo do que o normal.');
CALL sp_insert_habilidade('Clear Body', 'Impede que movimentos ou habilidades de outros Pokémon reduzam as estatísticas do Pokémon.');
CALL sp_insert_habilidade('Liquid Ooze', 'O líquido exsudado tem um cheiro forte, que prejudica os atacantes usando qualquer movimento de drenagem.');
CALL sp_insert_habilidade('Rock Head', 'Protege o Pokémon contra danos de recuo.');
CALL sp_insert_habilidade('Sturdy', 'Não pode ser nocauteado com um golpe. Movimentos de nocaute de um golpe também não podem derrubá-lo.');
CALL sp_insert_habilidade('Flame Body', 'O contato com o Pokémon pode queimar o atacante.');
CALL sp_insert_habilidade('Oblivious', 'O Pokémon está avuado, e isso o impede de se apaixonar ou cair em provocações.');
CALL sp_insert_habilidade('Own Tempo', 'Este Pokémon tem um ritmo próprio, o que evita que fique confuso.');
CALL sp_insert_habilidade('Regenerator', 'Restaura um pouco de HP quando retirado da batalha.');
CALL sp_insert_habilidade('Magnet Pull', 'Impede que Pokémon do tipo Steel escapem usando sua força magnética.');
CALL sp_insert_habilidade('Analytic', 'Aumenta o poder de movimento quando o Pokémon se move por último.');
CALL sp_insert_habilidade('Early Bird', 'O Pokémon desperta duas vezes mais rápido que outros Pokémon do sono');
CALL sp_insert_habilidade('Thick Fat', 'O Pokémon é protegido por uma camada espessa de gordura, que reduz pela metade o dano sofrido por movimentos do tipo Fogo e Gelo.');
CALL sp_insert_habilidade('Hydration', 'Cura condições de status se estiver chovendo.');
CALL sp_insert_habilidade('Ice Body', 'O Pokémon recupera HP gradualmente em uma tempestade de neve.');
CALL sp_insert_habilidade('Sticky Hold', 'Os itens mantidos pelo Pokémon ficam presos rapidamente e não podem ser removidos por outros Pokémon.');
CALL sp_insert_habilidade('Poison Touch', 'Pode envenenar um alvo quando o Pokémon faz contato.');
CALL sp_insert_habilidade('Shell Armor', 'Uma casca dura protege o Pokémon de ataques críticos.');
CALL sp_insert_habilidade('Skill Link', 'Maximiza o número de vezes que golpes múltiplos são acertados.');
CALL sp_insert_habilidade('Overcoat', 'Protege o Pokémon de coisas como areia, granizo e pólens.');
CALL sp_insert_habilidade('Levitate', 'Ao flutuar no ar, o Pokémon recebe imunidade total a todos os movimentos do tipo Terrestre.');
CALL sp_insert_habilidade('Cursed Body', 'Pode desativar um movimento usado no Pokémon.');
CALL sp_insert_habilidade('Weak Armor', 'Os ataques físicos ao Pokémon diminuem sua estatística de Defesa, mas aumentam drasticamente sua estatística de Velocidade.');
CALL sp_insert_habilidade('Insomnia', 'O Pokémon sofre de insônia e não consegue dormir.');
CALL sp_insert_habilidade('Forewarn', 'Quando entra em uma batalha, o Pokémon pode identificar um dos movimentos que um Pokémon adversário possui.');
CALL sp_insert_habilidade('Hyper Cutter', 'O Pokémon tem orgulho de suas pinças poderosas. Eles evitam que outros Pokémon diminuam suas estatísticas de ataque.');
CALL sp_insert_habilidade('Soundproof', 'A insonorização do próprio Pokémon dá imunidade total a todos os movimentos baseados em som.');
CALL sp_insert_habilidade('Aftermath', 'Causa dano ao atacante se ele entrar em contato com o Pokémon com um golpe final.');
CALL sp_insert_habilidade('Harvest', 'Pode criar outra Berry após uma ser usada.');
CALL sp_insert_habilidade('Battle Armor', 'A armadura rígida protege o Pokémon de ataques críticos.');
CALL sp_insert_habilidade('Reckless', 'Potencializa movimentos que causam dano de recuo.');
CALL sp_insert_habilidade('Unburden', 'Aumenta a estatística de velocidade se o item segurado pelo Pokémon for usado ou perdido.');
CALL sp_insert_habilidade('Iron Fist', 'Potencializa movimentos de soco.');
CALL sp_insert_habilidade('Neutralizing Gas', 'Se o Pokémon com Gás Neutralizante estiver na batalha, os efeitos de todas as Habilidades do Pokémon serão anulados ou não serão acionados.');
CALL sp_insert_habilidade('Natural Cure', 'Todas as condições de status são curadas quando o Pokémon é trocado.');
CALL sp_insert_habilidade('Serene Grace', 'Aumenta a probabilidade de ocorrência de efeitos adicionais durante o ataque.');
CALL sp_insert_habilidade('Healer', 'Às vezes cura a condição de status de um aliado.');
CALL sp_insert_habilidade('Leaf Guard', 'Evita condições de status em tempo ensolarado.');
CALL sp_insert_habilidade('Scrappy', 'O Pokémon pode atingir Pokémon do tipo Ghost com movimentos do tipo Normal e Lutador.');
CALL sp_insert_habilidade('Water Veil', 'O Pokémon é coberto por um véu de água, que evita que o Pokémon se queime.');
CALL sp_insert_habilidade('Illuminate', 'Aumenta a probabilidade de encontrar Pokémon selvagens ao iluminar os arredores.');
CALL sp_insert_habilidade('Filter', 'Reduz o poder de ataques superefetivos realizados.');
CALL sp_insert_habilidade('Mold Breaker', 'Os movimentos podem ser usados ​​no alvo independentemente de suas habilidades');
CALL sp_insert_habilidade('Moxie', 'O Pokémon mostra coragem, e isso aumenta a estatística de ataque após nocautear qualquer Pokémon.');
CALL sp_insert_habilidade('Rattled', 'Movimentos do tipo Dark, Ghost e Bug assustam o Pokémon e aumentam sua estatística de velocidade.');
CALL sp_insert_habilidade('Imposter', 'O Pokémon se transforma no Pokémon que está enfrentando.');
CALL sp_insert_habilidade('Adaptability', 'Potencializa movimentos do mesmo tipo do Pokémon.');
CALL sp_insert_habilidade('Anticipation', 'O Pokémon pode sentir os movimentos perigosos de um Pokémon adversário.');
CALL sp_insert_habilidade('Volt Absorb', 'Restaura HP se for atingido por um movimento do tipo Elétrico, em vez de sofrer dano.');
CALL sp_insert_habilidade('Quick Feet', 'Aumenta a estatística de velocidade se o Pokémon tiver uma condição de status.');
CALL sp_insert_habilidade('Trace', 'Quando entra em uma batalha, o Pokémon copia a habilidade de um Pokémon adversário.');
CALL sp_insert_habilidade('Download', 'Compara a Defesa e Sp de um Pokémon adversário. Estatísticas de Def antes de aumentar seu próprio Ataque ou Sp. Estatística de ataque – o que for mais eficaz.');
CALL sp_insert_habilidade('Pressure', 'Ao colocar pressão sobre o Pokémon adversário, aumenta o uso de PP.');
CALL sp_insert_habilidade('Immunity', 'O sistema imunológico do Pokémon evita que ele seja envenenado');
CALL sp_insert_habilidade('Snow Cloak', 'Aumenta a evasão em uma tempestade de neve.');
CALL sp_insert_habilidade('Marvel Scale', 'As maravilhosas escalas do Pokémon aumentam a estatística de Defesa se ele tiver uma condição de status.');
CALL sp_insert_habilidade('Multiscale', 'Reduz a quantidade de dano que o Pokémon sofre quando seu HP está cheio.');

/*INSERTS TIPOS DE CADA POKEMON*/
CALL sp_insert_pokemon_tipo(1, 2);
CALL sp_insert_pokemon_tipo(1, 7);
CALL sp_insert_pokemon_tipo(2, 2);
CALL sp_insert_pokemon_tipo(2, 7);
CALL sp_insert_pokemon_tipo(3, 2);
CALL sp_insert_pokemon_tipo(3, 7);
CALL sp_insert_pokemon_tipo(4, 3);
CALL sp_insert_pokemon_tipo(5, 3);
CALL sp_insert_pokemon_tipo(6, 3);
CALL sp_insert_pokemon_tipo(6, 6);
CALL sp_insert_pokemon_tipo(7, 4);
CALL sp_insert_pokemon_tipo(8, 4);
CALL sp_insert_pokemon_tipo(9, 4);
CALL sp_insert_pokemon_tipo(10, 10);
CALL sp_insert_pokemon_tipo(11, 10);
CALL sp_insert_pokemon_tipo(12, 10);
CALL sp_insert_pokemon_tipo(12, 6);
CALL sp_insert_pokemon_tipo(13, 10);
CALL sp_insert_pokemon_tipo(13, 7);
CALL sp_insert_pokemon_tipo(14, 10);
CALL sp_insert_pokemon_tipo(14, 7);
CALL sp_insert_pokemon_tipo(15, 10);
CALL sp_insert_pokemon_tipo(15, 7);
CALL sp_insert_pokemon_tipo(16, 1);
CALL sp_insert_pokemon_tipo(16, 6);
CALL sp_insert_pokemon_tipo(17, 1);
CALL sp_insert_pokemon_tipo(17, 6);
CALL sp_insert_pokemon_tipo(18, 1);
CALL sp_insert_pokemon_tipo(18, 6);
CALL sp_insert_pokemon_tipo(19, 1);
CALL sp_insert_pokemon_tipo(20, 1);
CALL sp_insert_pokemon_tipo(21, 1);
CALL sp_insert_pokemon_tipo(21, 6);
CALL sp_insert_pokemon_tipo(22, 1);
CALL sp_insert_pokemon_tipo(22, 6);
CALL sp_insert_pokemon_tipo(23, 7);
CALL sp_insert_pokemon_tipo(24, 7);
CALL sp_insert_pokemon_tipo(25, 12);
CALL sp_insert_pokemon_tipo(26, 12);
CALL sp_insert_pokemon_tipo(27, 8);
CALL sp_insert_pokemon_tipo(28, 8);
CALL sp_insert_pokemon_tipo(29, 7);
CALL sp_insert_pokemon_tipo(30, 7);
CALL sp_insert_pokemon_tipo(31, 7);
CALL sp_insert_pokemon_tipo(31, 8);
CALL sp_insert_pokemon_tipo(32, 7);
CALL sp_insert_pokemon_tipo(33, 7);
CALL sp_insert_pokemon_tipo(34, 7);
CALL sp_insert_pokemon_tipo(34, 8);
CALL sp_insert_pokemon_tipo(35, 18);
CALL sp_insert_pokemon_tipo(36, 18);
CALL sp_insert_pokemon_tipo(37, 3);
CALL sp_insert_pokemon_tipo(38, 3);
CALL sp_insert_pokemon_tipo(39, 1);
CALL sp_insert_pokemon_tipo(39, 18);
CALL sp_insert_pokemon_tipo(40, 1);
CALL sp_insert_pokemon_tipo(40, 18);
CALL sp_insert_pokemon_tipo(41, 7);
CALL sp_insert_pokemon_tipo(41, 6);
CALL sp_insert_pokemon_tipo(42, 7);
CALL sp_insert_pokemon_tipo(42, 6);
CALL sp_insert_pokemon_tipo(43, 2);
CALL sp_insert_pokemon_tipo(43, 7);
CALL sp_insert_pokemon_tipo(44, 2);
CALL sp_insert_pokemon_tipo(44, 7);
CALL sp_insert_pokemon_tipo(45, 2);
CALL sp_insert_pokemon_tipo(45, 7);
CALL sp_insert_pokemon_tipo(46, 10);
CALL sp_insert_pokemon_tipo(46, 2);
CALL sp_insert_pokemon_tipo(47, 10);
CALL sp_insert_pokemon_tipo(47, 2);
CALL sp_insert_pokemon_tipo(48, 10);
CALL sp_insert_pokemon_tipo(48, 7);
CALL sp_insert_pokemon_tipo(49, 10);
CALL sp_insert_pokemon_tipo(49, 7);
CALL sp_insert_pokemon_tipo(50, 8);
CALL sp_insert_pokemon_tipo(51, 8);
CALL sp_insert_pokemon_tipo(52, 1);
CALL sp_insert_pokemon_tipo(53, 1);
CALL sp_insert_pokemon_tipo(54, 4);
CALL sp_insert_pokemon_tipo(55, 4);
CALL sp_insert_pokemon_tipo(56, 5);
CALL sp_insert_pokemon_tipo(57, 5);
CALL sp_insert_pokemon_tipo(58, 3);
CALL sp_insert_pokemon_tipo(59, 3);
CALL sp_insert_pokemon_tipo(60, 4);
CALL sp_insert_pokemon_tipo(61, 4);
CALL sp_insert_pokemon_tipo(62, 4);
CALL sp_insert_pokemon_tipo(62, 5);
CALL sp_insert_pokemon_tipo(63, 13);
CALL sp_insert_pokemon_tipo(64, 13);
CALL sp_insert_pokemon_tipo(65, 13);
CALL sp_insert_pokemon_tipo(66, 5);
CALL sp_insert_pokemon_tipo(67, 5);
CALL sp_insert_pokemon_tipo(68, 5);
CALL sp_insert_pokemon_tipo(69, 2);
CALL sp_insert_pokemon_tipo(69, 7);
CALL sp_insert_pokemon_tipo(70, 2);
CALL sp_insert_pokemon_tipo(70, 7);
CALL sp_insert_pokemon_tipo(71, 2);
CALL sp_insert_pokemon_tipo(71, 7);
CALL sp_insert_pokemon_tipo(72, 4);
CALL sp_insert_pokemon_tipo(72, 7);
CALL sp_insert_pokemon_tipo(73, 4);
CALL sp_insert_pokemon_tipo(73, 7);
CALL sp_insert_pokemon_tipo(74, 9);
CALL sp_insert_pokemon_tipo(74, 8);
CALL sp_insert_pokemon_tipo(75, 9);
CALL sp_insert_pokemon_tipo(75, 8);
CALL sp_insert_pokemon_tipo(76, 9);
CALL sp_insert_pokemon_tipo(76, 8);
CALL sp_insert_pokemon_tipo(77, 3);
CALL sp_insert_pokemon_tipo(78, 3);
CALL sp_insert_pokemon_tipo(79, 4);
CALL sp_insert_pokemon_tipo(79, 13);
CALL sp_insert_pokemon_tipo(80, 4);
CALL sp_insert_pokemon_tipo(80, 13);
CALL sp_insert_pokemon_tipo(81, 12);
CALL sp_insert_pokemon_tipo(81, 17);
CALL sp_insert_pokemon_tipo(82, 12);
CALL sp_insert_pokemon_tipo(82, 17);
CALL sp_insert_pokemon_tipo(83, 1);
CALL sp_insert_pokemon_tipo(83, 6);
CALL sp_insert_pokemon_tipo(84, 1);
CALL sp_insert_pokemon_tipo(84, 6);
CALL sp_insert_pokemon_tipo(85, 1);
CALL sp_insert_pokemon_tipo(85, 6);
CALL sp_insert_pokemon_tipo(86, 4);
CALL sp_insert_pokemon_tipo(87, 4);
CALL sp_insert_pokemon_tipo(87, 14);
CALL sp_insert_pokemon_tipo(88, 7);
CALL sp_insert_pokemon_tipo(89, 7);
CALL sp_insert_pokemon_tipo(90, 4);
CALL sp_insert_pokemon_tipo(91, 4);
CALL sp_insert_pokemon_tipo(91, 14);
CALL sp_insert_pokemon_tipo(92, 11);
CALL sp_insert_pokemon_tipo(92, 7);
CALL sp_insert_pokemon_tipo(93, 11);
CALL sp_insert_pokemon_tipo(93, 7);
CALL sp_insert_pokemon_tipo(94, 11);
CALL sp_insert_pokemon_tipo(94, 7);
CALL sp_insert_pokemon_tipo(95, 9);
CALL sp_insert_pokemon_tipo(95, 8);
CALL sp_insert_pokemon_tipo(96, 13);
CALL sp_insert_pokemon_tipo(97, 13);
CALL sp_insert_pokemon_tipo(98, 4);
CALL sp_insert_pokemon_tipo(99, 4);
CALL sp_insert_pokemon_tipo(100, 12);
CALL sp_insert_pokemon_tipo(101, 12);
CALL sp_insert_pokemon_tipo(102, 2);
CALL sp_insert_pokemon_tipo(102, 13);
CALL sp_insert_pokemon_tipo(103, 2);
CALL sp_insert_pokemon_tipo(103, 13);
CALL sp_insert_pokemon_tipo(104, 8);
CALL sp_insert_pokemon_tipo(105, 8);
CALL sp_insert_pokemon_tipo(106, 5);
CALL sp_insert_pokemon_tipo(107, 5);
CALL sp_insert_pokemon_tipo(108, 1);
CALL sp_insert_pokemon_tipo(109, 7);
CALL sp_insert_pokemon_tipo(110, 7);
CALL sp_insert_pokemon_tipo(111, 9);
CALL sp_insert_pokemon_tipo(111, 8);
CALL sp_insert_pokemon_tipo(112, 9);
CALL sp_insert_pokemon_tipo(113, 1);
CALL sp_insert_pokemon_tipo(114, 2);
CALL sp_insert_pokemon_tipo(115, 1);
CALL sp_insert_pokemon_tipo(116, 4);
CALL sp_insert_pokemon_tipo(117, 4);
CALL sp_insert_pokemon_tipo(118, 4);
CALL sp_insert_pokemon_tipo(119, 4);
CALL sp_insert_pokemon_tipo(120, 4);
CALL sp_insert_pokemon_tipo(121, 4);
CALL sp_insert_pokemon_tipo(121, 13);
CALL sp_insert_pokemon_tipo(122, 13);
CALL sp_insert_pokemon_tipo(122, 18);
CALL sp_insert_pokemon_tipo(123, 10);
CALL sp_insert_pokemon_tipo(123, 6);
CALL sp_insert_pokemon_tipo(124, 14);
CALL sp_insert_pokemon_tipo(124, 13);
CALL sp_insert_pokemon_tipo(125, 12);
CALL sp_insert_pokemon_tipo(126, 3);
CALL sp_insert_pokemon_tipo(127, 10);
CALL sp_insert_pokemon_tipo(128, 1);
CALL sp_insert_pokemon_tipo(129, 4);
CALL sp_insert_pokemon_tipo(130, 4);
CALL sp_insert_pokemon_tipo(130, 6);
CALL sp_insert_pokemon_tipo(131, 4);
CALL sp_insert_pokemon_tipo(131, 14);
CALL sp_insert_pokemon_tipo(132, 1);
CALL sp_insert_pokemon_tipo(133, 1);
CALL sp_insert_pokemon_tipo(134, 4);
CALL sp_insert_pokemon_tipo(135, 12);
CALL sp_insert_pokemon_tipo(136, 3);
CALL sp_insert_pokemon_tipo(137, 1);
CALL sp_insert_pokemon_tipo(138, 9);
CALL sp_insert_pokemon_tipo(138, 4);
CALL sp_insert_pokemon_tipo(139, 9);
CALL sp_insert_pokemon_tipo(139, 4);
CALL sp_insert_pokemon_tipo(140, 9);
CALL sp_insert_pokemon_tipo(140, 4);
CALL sp_insert_pokemon_tipo(141, 9);
CALL sp_insert_pokemon_tipo(141, 4);
CALL sp_insert_pokemon_tipo(142, 9);
CALL sp_insert_pokemon_tipo(142, 6);
CALL sp_insert_pokemon_tipo(143, 1);
CALL sp_insert_pokemon_tipo(144, 12);
CALL sp_insert_pokemon_tipo(144, 6);
CALL sp_insert_pokemon_tipo(145, 12);
CALL sp_insert_pokemon_tipo(145, 6);
CALL sp_insert_pokemon_tipo(146, 3);
CALL sp_insert_pokemon_tipo(146, 6);
CALL sp_insert_pokemon_tipo(147, 15);
CALL sp_insert_pokemon_tipo(148, 15);
CALL sp_insert_pokemon_tipo(149, 15);
CALL sp_insert_pokemon_tipo(149, 6);
CALL sp_insert_pokemon_tipo(150, 13);
CALL sp_insert_pokemon_tipo(151, 13);

/*INSERTS FRAQUEZAS DOS POKEMONS*/
CALL sp_insert_pokemon_fraqueza(1, 3);
CALL sp_insert_pokemon_fraqueza(1, 14);
CALL sp_insert_pokemon_fraqueza(1, 6);
CALL sp_insert_pokemon_fraqueza(1, 13);
CALL sp_insert_pokemon_fraqueza(2, 3);
CALL sp_insert_pokemon_fraqueza(2, 14);
CALL sp_insert_pokemon_fraqueza(2, 6);
CALL sp_insert_pokemon_fraqueza(2, 13);
CALL sp_insert_pokemon_fraqueza(3, 3);
CALL sp_insert_pokemon_fraqueza(3, 14);
CALL sp_insert_pokemon_fraqueza(3, 6);
CALL sp_insert_pokemon_fraqueza(3, 13);
CALL sp_insert_pokemon_fraqueza(4, 4);
CALL sp_insert_pokemon_fraqueza(4, 8);
CALL sp_insert_pokemon_fraqueza(4, 9);
CALL sp_insert_pokemon_fraqueza(5, 4);
CALL sp_insert_pokemon_fraqueza(5, 8);
CALL sp_insert_pokemon_fraqueza(5, 9);
CALL sp_insert_pokemon_fraqueza(6, 4);
CALL sp_insert_pokemon_fraqueza(6, 12);
CALL sp_insert_pokemon_fraqueza(6, 9);
CALL sp_insert_pokemon_fraqueza(7, 2);
CALL sp_insert_pokemon_fraqueza(7, 12);
CALL sp_insert_pokemon_fraqueza(8, 2);
CALL sp_insert_pokemon_fraqueza(8, 12);
CALL sp_insert_pokemon_fraqueza(9, 2);
CALL sp_insert_pokemon_fraqueza(9, 12);
CALL sp_insert_pokemon_fraqueza(10, 3);
CALL sp_insert_pokemon_fraqueza(10, 6);
CALL sp_insert_pokemon_fraqueza(10, 9);
CALL sp_insert_pokemon_fraqueza(11, 3);
CALL sp_insert_pokemon_fraqueza(11, 6);
CALL sp_insert_pokemon_fraqueza(11, 9);
CALL sp_insert_pokemon_fraqueza(12, 3);
CALL sp_insert_pokemon_fraqueza(12, 12);
CALL sp_insert_pokemon_fraqueza(12, 14);
CALL sp_insert_pokemon_fraqueza(12, 6);
CALL sp_insert_pokemon_fraqueza(12, 9);
CALL sp_insert_pokemon_fraqueza(13, 3);
CALL sp_insert_pokemon_fraqueza(13, 6);
CALL sp_insert_pokemon_fraqueza(13, 13);
CALL sp_insert_pokemon_fraqueza(13, 9);
CALL sp_insert_pokemon_fraqueza(14, 3);
CALL sp_insert_pokemon_fraqueza(14, 6);
CALL sp_insert_pokemon_fraqueza(14, 13);
CALL sp_insert_pokemon_fraqueza(14, 9);
CALL sp_insert_pokemon_fraqueza(15, 3);
CALL sp_insert_pokemon_fraqueza(15, 6);
CALL sp_insert_pokemon_fraqueza(15, 13);
CALL sp_insert_pokemon_fraqueza(15, 9);
CALL sp_insert_pokemon_fraqueza(16, 12);
CALL sp_insert_pokemon_fraqueza(16, 14);
CALL sp_insert_pokemon_fraqueza(16, 9);
CALL sp_insert_pokemon_fraqueza(17, 12);
CALL sp_insert_pokemon_fraqueza(17, 14);
CALL sp_insert_pokemon_fraqueza(17, 9);
CALL sp_insert_pokemon_fraqueza(18, 12);
CALL sp_insert_pokemon_fraqueza(18, 14);
CALL sp_insert_pokemon_fraqueza(18, 9);
CALL sp_insert_pokemon_fraqueza(19, 5);
CALL sp_insert_pokemon_fraqueza(20, 5);
CALL sp_insert_pokemon_fraqueza(21, 12);
CALL sp_insert_pokemon_fraqueza(21, 14);
CALL sp_insert_pokemon_fraqueza(21, 9);
CALL sp_insert_pokemon_fraqueza(22, 12);
CALL sp_insert_pokemon_fraqueza(22, 14);
CALL sp_insert_pokemon_fraqueza(22, 9);
CALL sp_insert_pokemon_fraqueza(23, 13);
CALL sp_insert_pokemon_fraqueza(23, 8);
CALL sp_insert_pokemon_fraqueza(24, 13);
CALL sp_insert_pokemon_fraqueza(24, 8);
CALL sp_insert_pokemon_fraqueza(25, 8);
CALL sp_insert_pokemon_fraqueza(26, 8);
CALL sp_insert_pokemon_fraqueza(27, 4);
CALL sp_insert_pokemon_fraqueza(27, 2);
CALL sp_insert_pokemon_fraqueza(27, 14);
CALL sp_insert_pokemon_fraqueza(28, 4);
CALL sp_insert_pokemon_fraqueza(28, 2);
CALL sp_insert_pokemon_fraqueza(28, 14);
CALL sp_insert_pokemon_fraqueza(29, 8);
CALL sp_insert_pokemon_fraqueza(29, 13);
CALL sp_insert_pokemon_fraqueza(30, 8);
CALL sp_insert_pokemon_fraqueza(30, 13);
CALL sp_insert_pokemon_fraqueza(31, 8);
CALL sp_insert_pokemon_fraqueza(31, 13);
CALL sp_insert_pokemon_fraqueza(31, 4);
CALL sp_insert_pokemon_fraqueza(31, 14);
CALL sp_insert_pokemon_fraqueza(32, 8);
CALL sp_insert_pokemon_fraqueza(32, 13);
CALL sp_insert_pokemon_fraqueza(33, 8);
CALL sp_insert_pokemon_fraqueza(33, 13);
CALL sp_insert_pokemon_fraqueza(34, 8);
CALL sp_insert_pokemon_fraqueza(34, 13);
CALL sp_insert_pokemon_fraqueza(34, 4);
CALL sp_insert_pokemon_fraqueza(34, 14);
CALL sp_insert_pokemon_fraqueza(35, 7);
CALL sp_insert_pokemon_fraqueza(35, 17);
CALL sp_insert_pokemon_fraqueza(36, 7);
CALL sp_insert_pokemon_fraqueza(36, 17);
CALL sp_insert_pokemon_fraqueza(37, 4);
CALL sp_insert_pokemon_fraqueza(37, 8);
CALL sp_insert_pokemon_fraqueza(37, 9);
CALL sp_insert_pokemon_fraqueza(38, 4);
CALL sp_insert_pokemon_fraqueza(38, 8);
CALL sp_insert_pokemon_fraqueza(38, 9);
CALL sp_insert_pokemon_fraqueza(39, 7);
CALL sp_insert_pokemon_fraqueza(39, 17);
CALL sp_insert_pokemon_fraqueza(40, 7);
CALL sp_insert_pokemon_fraqueza(40, 17);
CALL sp_insert_pokemon_fraqueza(41, 12);
CALL sp_insert_pokemon_fraqueza(41, 14);
CALL sp_insert_pokemon_fraqueza(41, 13);
CALL sp_insert_pokemon_fraqueza(41, 9);
CALL sp_insert_pokemon_fraqueza(42, 12);
CALL sp_insert_pokemon_fraqueza(42, 14);
CALL sp_insert_pokemon_fraqueza(42, 13);
CALL sp_insert_pokemon_fraqueza(42, 9);
CALL sp_insert_pokemon_fraqueza(43, 3);
CALL sp_insert_pokemon_fraqueza(43, 14);
CALL sp_insert_pokemon_fraqueza(43, 6);
CALL sp_insert_pokemon_fraqueza(43, 13);
CALL sp_insert_pokemon_fraqueza(44, 3);
CALL sp_insert_pokemon_fraqueza(44, 14);
CALL sp_insert_pokemon_fraqueza(44, 6);
CALL sp_insert_pokemon_fraqueza(44, 13);
CALL sp_insert_pokemon_fraqueza(45, 3);
CALL sp_insert_pokemon_fraqueza(45, 14);
CALL sp_insert_pokemon_fraqueza(45, 6);
CALL sp_insert_pokemon_fraqueza(45, 13);
CALL sp_insert_pokemon_fraqueza(46, 3);
CALL sp_insert_pokemon_fraqueza(46, 14);
CALL sp_insert_pokemon_fraqueza(46, 7);
CALL sp_insert_pokemon_fraqueza(46, 6);
CALL sp_insert_pokemon_fraqueza(46, 10);
CALL sp_insert_pokemon_fraqueza(46, 9);
CALL sp_insert_pokemon_fraqueza(47, 3);
CALL sp_insert_pokemon_fraqueza(47, 14);
CALL sp_insert_pokemon_fraqueza(47, 7);
CALL sp_insert_pokemon_fraqueza(47, 6);
CALL sp_insert_pokemon_fraqueza(47, 10);
CALL sp_insert_pokemon_fraqueza(47, 9);
CALL sp_insert_pokemon_fraqueza(48, 3);
CALL sp_insert_pokemon_fraqueza(48, 6);
CALL sp_insert_pokemon_fraqueza(48, 13);
CALL sp_insert_pokemon_fraqueza(48, 9);
CALL sp_insert_pokemon_fraqueza(49, 3);
CALL sp_insert_pokemon_fraqueza(49, 6);
CALL sp_insert_pokemon_fraqueza(49, 13);
CALL sp_insert_pokemon_fraqueza(49, 9);
CALL sp_insert_pokemon_fraqueza(50, 4);
CALL sp_insert_pokemon_fraqueza(50, 3);
CALL sp_insert_pokemon_fraqueza(50, 14);
CALL sp_insert_pokemon_fraqueza(51, 4);
CALL sp_insert_pokemon_fraqueza(51, 3);
CALL sp_insert_pokemon_fraqueza(51, 14);
CALL sp_insert_pokemon_fraqueza(52, 5);
CALL sp_insert_pokemon_fraqueza(53, 5);
CALL sp_insert_pokemon_fraqueza(54, 3);
CALL sp_insert_pokemon_fraqueza(54, 12);
CALL sp_insert_pokemon_fraqueza(55, 3);
CALL sp_insert_pokemon_fraqueza(55, 12);
CALL sp_insert_pokemon_fraqueza(56, 6);
CALL sp_insert_pokemon_fraqueza(56, 13);
CALL sp_insert_pokemon_fraqueza(56, 18);
CALL sp_insert_pokemon_fraqueza(57, 6);
CALL sp_insert_pokemon_fraqueza(57, 13);
CALL sp_insert_pokemon_fraqueza(57, 18);
CALL sp_insert_pokemon_fraqueza(58, 4);
CALL sp_insert_pokemon_fraqueza(58, 8);
CALL sp_insert_pokemon_fraqueza(58, 9);
CALL sp_insert_pokemon_fraqueza(59, 4);
CALL sp_insert_pokemon_fraqueza(59, 8);
CALL sp_insert_pokemon_fraqueza(59, 9);
CALL sp_insert_pokemon_fraqueza(60, 2);
CALL sp_insert_pokemon_fraqueza(60, 12);
CALL sp_insert_pokemon_fraqueza(61, 2);
CALL sp_insert_pokemon_fraqueza(61, 12);
CALL sp_insert_pokemon_fraqueza(62, 2);
CALL sp_insert_pokemon_fraqueza(62, 12);
CALL sp_insert_pokemon_fraqueza(62, 6);
CALL sp_insert_pokemon_fraqueza(62, 13);
CALL sp_insert_pokemon_fraqueza(62, 18);
CALL sp_insert_pokemon_fraqueza(63, 7);
CALL sp_insert_pokemon_fraqueza(63, 11);
CALL sp_insert_pokemon_fraqueza(63, 16);
CALL sp_insert_pokemon_fraqueza(64, 7);
CALL sp_insert_pokemon_fraqueza(64, 11);
CALL sp_insert_pokemon_fraqueza(64, 16);
CALL sp_insert_pokemon_fraqueza(65, 7);
CALL sp_insert_pokemon_fraqueza(65, 11);
CALL sp_insert_pokemon_fraqueza(65, 16);
CALL sp_insert_pokemon_fraqueza(66, 6);
CALL sp_insert_pokemon_fraqueza(66, 13);
CALL sp_insert_pokemon_fraqueza(66, 18);
CALL sp_insert_pokemon_fraqueza(67, 6);
CALL sp_insert_pokemon_fraqueza(67, 13);
CALL sp_insert_pokemon_fraqueza(67, 18);
CALL sp_insert_pokemon_fraqueza(68, 6);
CALL sp_insert_pokemon_fraqueza(68, 13);
CALL sp_insert_pokemon_fraqueza(68, 18);
CALL sp_insert_pokemon_fraqueza(69, 3);
CALL sp_insert_pokemon_fraqueza(69, 14);
CALL sp_insert_pokemon_fraqueza(69, 6);
CALL sp_insert_pokemon_fraqueza(69, 13);
CALL sp_insert_pokemon_fraqueza(70, 3);
CALL sp_insert_pokemon_fraqueza(70, 14);
CALL sp_insert_pokemon_fraqueza(70, 6);
CALL sp_insert_pokemon_fraqueza(70, 13);
CALL sp_insert_pokemon_fraqueza(71, 3);
CALL sp_insert_pokemon_fraqueza(71, 14);
CALL sp_insert_pokemon_fraqueza(71, 6);
CALL sp_insert_pokemon_fraqueza(71, 13);
CALL sp_insert_pokemon_fraqueza(72, 12);
CALL sp_insert_pokemon_fraqueza(72, 8);
CALL sp_insert_pokemon_fraqueza(72, 13);
CALL sp_insert_pokemon_fraqueza(73, 12);
CALL sp_insert_pokemon_fraqueza(73, 8);
CALL sp_insert_pokemon_fraqueza(73, 13);
CALL sp_insert_pokemon_fraqueza(74, 4);
CALL sp_insert_pokemon_fraqueza(74, 2);
CALL sp_insert_pokemon_fraqueza(74, 14);
CALL sp_insert_pokemon_fraqueza(74, 6);
CALL sp_insert_pokemon_fraqueza(74, 8);
CALL sp_insert_pokemon_fraqueza(74, 17);
CALL sp_insert_pokemon_fraqueza(75, 4);
CALL sp_insert_pokemon_fraqueza(75, 2);
CALL sp_insert_pokemon_fraqueza(75, 14);
CALL sp_insert_pokemon_fraqueza(75, 6);
CALL sp_insert_pokemon_fraqueza(75, 8);
CALL sp_insert_pokemon_fraqueza(75, 17);
CALL sp_insert_pokemon_fraqueza(76, 4);
CALL sp_insert_pokemon_fraqueza(76, 2);
CALL sp_insert_pokemon_fraqueza(76, 14);
CALL sp_insert_pokemon_fraqueza(76, 6);
CALL sp_insert_pokemon_fraqueza(76, 8);
CALL sp_insert_pokemon_fraqueza(76, 17);
CALL sp_insert_pokemon_fraqueza(77, 4);
CALL sp_insert_pokemon_fraqueza(77, 8);
CALL sp_insert_pokemon_fraqueza(77, 9);
CALL sp_insert_pokemon_fraqueza(78, 4);
CALL sp_insert_pokemon_fraqueza(78, 8);
CALL sp_insert_pokemon_fraqueza(78, 9);
CALL sp_insert_pokemon_fraqueza(79, 2);
CALL sp_insert_pokemon_fraqueza(79, 12);
CALL sp_insert_pokemon_fraqueza(79, 10);
CALL sp_insert_pokemon_fraqueza(79, 11);
CALL sp_insert_pokemon_fraqueza(79, 16);
CALL sp_insert_pokemon_fraqueza(80, 2);
CALL sp_insert_pokemon_fraqueza(80, 12);
CALL sp_insert_pokemon_fraqueza(80, 10);
CALL sp_insert_pokemon_fraqueza(80, 11);
CALL sp_insert_pokemon_fraqueza(80, 16);
CALL sp_insert_pokemon_fraqueza(81, 3);
CALL sp_insert_pokemon_fraqueza(81, 5);
CALL sp_insert_pokemon_fraqueza(81, 8);
CALL sp_insert_pokemon_fraqueza(82, 3);
CALL sp_insert_pokemon_fraqueza(82, 5);
CALL sp_insert_pokemon_fraqueza(82, 8);
CALL sp_insert_pokemon_fraqueza(83, 12);
CALL sp_insert_pokemon_fraqueza(83, 14);
CALL sp_insert_pokemon_fraqueza(83, 9);
CALL sp_insert_pokemon_fraqueza(84, 12);
CALL sp_insert_pokemon_fraqueza(84, 14);
CALL sp_insert_pokemon_fraqueza(84, 9);
CALL sp_insert_pokemon_fraqueza(85, 12);
CALL sp_insert_pokemon_fraqueza(85, 14);
CALL sp_insert_pokemon_fraqueza(85, 9);
CALL sp_insert_pokemon_fraqueza(86, 2);
CALL sp_insert_pokemon_fraqueza(86, 12);
CALL sp_insert_pokemon_fraqueza(87, 2);
CALL sp_insert_pokemon_fraqueza(87, 12);
CALL sp_insert_pokemon_fraqueza(87, 5);
CALL sp_insert_pokemon_fraqueza(87, 9);
CALL sp_insert_pokemon_fraqueza(88, 8);
CALL sp_insert_pokemon_fraqueza(88, 13);
CALL sp_insert_pokemon_fraqueza(89, 8);
CALL sp_insert_pokemon_fraqueza(89, 13);
CALL sp_insert_pokemon_fraqueza(90, 2);
CALL sp_insert_pokemon_fraqueza(90, 12);
CALL sp_insert_pokemon_fraqueza(91, 2);
CALL sp_insert_pokemon_fraqueza(91, 12);
CALL sp_insert_pokemon_fraqueza(91, 5);
CALL sp_insert_pokemon_fraqueza(91, 9);
CALL sp_insert_pokemon_fraqueza(92, 8);
CALL sp_insert_pokemon_fraqueza(92, 13);
CALL sp_insert_pokemon_fraqueza(92, 11);
CALL sp_insert_pokemon_fraqueza(92, 16);
CALL sp_insert_pokemon_fraqueza(93, 8);
CALL sp_insert_pokemon_fraqueza(93, 13);
CALL sp_insert_pokemon_fraqueza(93, 11);
CALL sp_insert_pokemon_fraqueza(93, 16);
CALL sp_insert_pokemon_fraqueza(94, 8);
CALL sp_insert_pokemon_fraqueza(94, 13);
CALL sp_insert_pokemon_fraqueza(94, 11);
CALL sp_insert_pokemon_fraqueza(94, 16);
CALL sp_insert_pokemon_fraqueza(95, 4);
CALL sp_insert_pokemon_fraqueza(95, 2);
CALL sp_insert_pokemon_fraqueza(95, 14);
CALL sp_insert_pokemon_fraqueza(95, 5);
CALL sp_insert_pokemon_fraqueza(95, 8);
CALL sp_insert_pokemon_fraqueza(95, 17);
CALL sp_insert_pokemon_fraqueza(96, 10);
CALL sp_insert_pokemon_fraqueza(96, 11);
CALL sp_insert_pokemon_fraqueza(96, 16);
CALL sp_insert_pokemon_fraqueza(97, 10);
CALL sp_insert_pokemon_fraqueza(97, 11);
CALL sp_insert_pokemon_fraqueza(97, 16);
CALL sp_insert_pokemon_fraqueza(98, 2);
CALL sp_insert_pokemon_fraqueza(98, 12);
CALL sp_insert_pokemon_fraqueza(99, 2);
CALL sp_insert_pokemon_fraqueza(99, 12);
CALL sp_insert_pokemon_fraqueza(100, 8);
CALL sp_insert_pokemon_fraqueza(101, 8);
CALL sp_insert_pokemon_fraqueza(102, 3);
CALL sp_insert_pokemon_fraqueza(102, 14);
CALL sp_insert_pokemon_fraqueza(102, 7);
CALL sp_insert_pokemon_fraqueza(102, 6);
CALL sp_insert_pokemon_fraqueza(102, 10);
CALL sp_insert_pokemon_fraqueza(102, 11);
CALL sp_insert_pokemon_fraqueza(102, 16);
CALL sp_insert_pokemon_fraqueza(103, 3);
CALL sp_insert_pokemon_fraqueza(103, 14);
CALL sp_insert_pokemon_fraqueza(103, 7);
CALL sp_insert_pokemon_fraqueza(103, 6);
CALL sp_insert_pokemon_fraqueza(103, 10);
CALL sp_insert_pokemon_fraqueza(103, 11);
CALL sp_insert_pokemon_fraqueza(103, 16);
CALL sp_insert_pokemon_fraqueza(104, 4);
CALL sp_insert_pokemon_fraqueza(104, 2);
CALL sp_insert_pokemon_fraqueza(104, 14);
CALL sp_insert_pokemon_fraqueza(105, 4);
CALL sp_insert_pokemon_fraqueza(105, 2);
CALL sp_insert_pokemon_fraqueza(105, 14);
CALL sp_insert_pokemon_fraqueza(106, 6);
CALL sp_insert_pokemon_fraqueza(106, 13);
CALL sp_insert_pokemon_fraqueza(106, 18);
CALL sp_insert_pokemon_fraqueza(107, 6);
CALL sp_insert_pokemon_fraqueza(107, 13);
CALL sp_insert_pokemon_fraqueza(107, 18);
CALL sp_insert_pokemon_fraqueza(108, 5);
CALL sp_insert_pokemon_fraqueza(109, 8);
CALL sp_insert_pokemon_fraqueza(109, 13);
CALL sp_insert_pokemon_fraqueza(110, 8);
CALL sp_insert_pokemon_fraqueza(110, 13);
CALL sp_insert_pokemon_fraqueza(111, 4);
CALL sp_insert_pokemon_fraqueza(111, 2);
CALL sp_insert_pokemon_fraqueza(111, 14);
CALL sp_insert_pokemon_fraqueza(111, 5);
CALL sp_insert_pokemon_fraqueza(111, 8);
CALL sp_insert_pokemon_fraqueza(111, 17);
CALL sp_insert_pokemon_fraqueza(112, 4);
CALL sp_insert_pokemon_fraqueza(112, 2);
CALL sp_insert_pokemon_fraqueza(112, 14);
CALL sp_insert_pokemon_fraqueza(112, 5);
CALL sp_insert_pokemon_fraqueza(112, 8);
CALL sp_insert_pokemon_fraqueza(112, 17);
CALL sp_insert_pokemon_fraqueza(113, 5);
CALL sp_insert_pokemon_fraqueza(114, 3);
CALL sp_insert_pokemon_fraqueza(114, 14);
CALL sp_insert_pokemon_fraqueza(114, 7);
CALL sp_insert_pokemon_fraqueza(114, 6);
CALL sp_insert_pokemon_fraqueza(114, 10);
CALL sp_insert_pokemon_fraqueza(115, 5);
CALL sp_insert_pokemon_fraqueza(116, 12);
CALL sp_insert_pokemon_fraqueza(116, 2);
CALL sp_insert_pokemon_fraqueza(117, 12);
CALL sp_insert_pokemon_fraqueza(117, 2);
CALL sp_insert_pokemon_fraqueza(118, 12);
CALL sp_insert_pokemon_fraqueza(118, 2);
CALL sp_insert_pokemon_fraqueza(119, 12);
CALL sp_insert_pokemon_fraqueza(119, 2);
CALL sp_insert_pokemon_fraqueza(120, 12);
CALL sp_insert_pokemon_fraqueza(120, 2);
CALL sp_insert_pokemon_fraqueza(121, 12);
CALL sp_insert_pokemon_fraqueza(121, 2);
CALL sp_insert_pokemon_fraqueza(121, 10);
CALL sp_insert_pokemon_fraqueza(121, 11);
CALL sp_insert_pokemon_fraqueza(121, 16);
CALL sp_insert_pokemon_fraqueza(122, 7);
CALL sp_insert_pokemon_fraqueza(122, 11);
CALL sp_insert_pokemon_fraqueza(122, 17);
CALL sp_insert_pokemon_fraqueza(123, 3);
CALL sp_insert_pokemon_fraqueza(123, 12);
CALL sp_insert_pokemon_fraqueza(123, 14);
CALL sp_insert_pokemon_fraqueza(123, 6);
CALL sp_insert_pokemon_fraqueza(123, 9);
CALL sp_insert_pokemon_fraqueza(124, 3);
CALL sp_insert_pokemon_fraqueza(124, 10);
CALL sp_insert_pokemon_fraqueza(124, 9);
CALL sp_insert_pokemon_fraqueza(124, 11);
CALL sp_insert_pokemon_fraqueza(124, 16);
CALL sp_insert_pokemon_fraqueza(124, 17);
CALL sp_insert_pokemon_fraqueza(125, 8);
CALL sp_insert_pokemon_fraqueza(126, 4);
CALL sp_insert_pokemon_fraqueza(126, 8);
CALL sp_insert_pokemon_fraqueza(126, 9);
CALL sp_insert_pokemon_fraqueza(127, 3);
CALL sp_insert_pokemon_fraqueza(127, 6);
CALL sp_insert_pokemon_fraqueza(127, 9);
CALL sp_insert_pokemon_fraqueza(128, 5);
CALL sp_insert_pokemon_fraqueza(129, 2);
CALL sp_insert_pokemon_fraqueza(129, 12);
CALL sp_insert_pokemon_fraqueza(130, 12);
CALL sp_insert_pokemon_fraqueza(130, 9);
CALL sp_insert_pokemon_fraqueza(131, 2);
CALL sp_insert_pokemon_fraqueza(131, 12);
CALL sp_insert_pokemon_fraqueza(131, 5);
CALL sp_insert_pokemon_fraqueza(131, 9);
CALL sp_insert_pokemon_fraqueza(132, 5);
CALL sp_insert_pokemon_fraqueza(133, 5);
CALL sp_insert_pokemon_fraqueza(134, 2);
CALL sp_insert_pokemon_fraqueza(134, 12);
CALL sp_insert_pokemon_fraqueza(135, 8);
CALL sp_insert_pokemon_fraqueza(136, 4);
CALL sp_insert_pokemon_fraqueza(136, 8);
CALL sp_insert_pokemon_fraqueza(136, 9);
CALL sp_insert_pokemon_fraqueza(137, 5);
CALL sp_insert_pokemon_fraqueza(138, 2);
CALL sp_insert_pokemon_fraqueza(138, 12);
CALL sp_insert_pokemon_fraqueza(138, 5);
CALL sp_insert_pokemon_fraqueza(138, 8);
CALL sp_insert_pokemon_fraqueza(139, 2);
CALL sp_insert_pokemon_fraqueza(139, 12);
CALL sp_insert_pokemon_fraqueza(139, 5);
CALL sp_insert_pokemon_fraqueza(139, 8);
CALL sp_insert_pokemon_fraqueza(140, 2);
CALL sp_insert_pokemon_fraqueza(140, 12);
CALL sp_insert_pokemon_fraqueza(140, 5);
CALL sp_insert_pokemon_fraqueza(140, 8);
CALL sp_insert_pokemon_fraqueza(141, 2);
CALL sp_insert_pokemon_fraqueza(141, 12);
CALL sp_insert_pokemon_fraqueza(141, 5);
CALL sp_insert_pokemon_fraqueza(141, 8);
CALL sp_insert_pokemon_fraqueza(142, 4);
CALL sp_insert_pokemon_fraqueza(142, 12);
CALL sp_insert_pokemon_fraqueza(142, 14);
CALL sp_insert_pokemon_fraqueza(142, 9);
CALL sp_insert_pokemon_fraqueza(142, 17);
CALL sp_insert_pokemon_fraqueza(143, 5);
CALL sp_insert_pokemon_fraqueza(144, 3);
CALL sp_insert_pokemon_fraqueza(144, 12);
CALL sp_insert_pokemon_fraqueza(144, 9);
CALL sp_insert_pokemon_fraqueza(144, 17);
CALL sp_insert_pokemon_fraqueza(145, 14);
CALL sp_insert_pokemon_fraqueza(145, 9);
CALL sp_insert_pokemon_fraqueza(146, 4);
CALL sp_insert_pokemon_fraqueza(146, 12);
CALL sp_insert_pokemon_fraqueza(146, 9);
CALL sp_insert_pokemon_fraqueza(147, 14);
CALL sp_insert_pokemon_fraqueza(147, 15);
CALL sp_insert_pokemon_fraqueza(147, 18);
CALL sp_insert_pokemon_fraqueza(148, 14);
CALL sp_insert_pokemon_fraqueza(148, 15);
CALL sp_insert_pokemon_fraqueza(148, 18);
CALL sp_insert_pokemon_fraqueza(149, 14);
CALL sp_insert_pokemon_fraqueza(149, 15);
CALL sp_insert_pokemon_fraqueza(149, 18);
CALL sp_insert_pokemon_fraqueza(149, 9);
CALL sp_insert_pokemon_fraqueza(150, 10);
CALL sp_insert_pokemon_fraqueza(150, 11);
CALL sp_insert_pokemon_fraqueza(150, 16);
CALL sp_insert_pokemon_fraqueza(151, 10);
CALL sp_insert_pokemon_fraqueza(151, 11);
CALL sp_insert_pokemon_fraqueza(151, 16);

/*INSERT DAS EVOLUÇÕES DOS POKEMONS*/
CALL sp_insert_pokemon_evolucao(1, 1);
CALL sp_insert_pokemon_evolucao(2, 2);
CALL sp_insert_pokemon_evolucao(4, 3);
CALL sp_insert_pokemon_evolucao(5, 4);
CALL sp_insert_pokemon_evolucao(7, 5);
CALL sp_insert_pokemon_evolucao(8, 6);
CALL sp_insert_pokemon_evolucao(10, 7);
CALL sp_insert_pokemon_evolucao(11, 8);
CALL sp_insert_pokemon_evolucao(13, 9);
CALL sp_insert_pokemon_evolucao(14, 10);
CALL sp_insert_pokemon_evolucao(16, 11);
CALL sp_insert_pokemon_evolucao(17, 12);
CALL sp_insert_pokemon_evolucao(19, 13);
CALL sp_insert_pokemon_evolucao(21, 14);
CALL sp_insert_pokemon_evolucao(23, 15);
CALL sp_insert_pokemon_evolucao(25, 16);
CALL sp_insert_pokemon_evolucao(27, 17);
CALL sp_insert_pokemon_evolucao(29, 18);
CALL sp_insert_pokemon_evolucao(30, 19);
CALL sp_insert_pokemon_evolucao(32, 20);
CALL sp_insert_pokemon_evolucao(33, 21);
CALL sp_insert_pokemon_evolucao(35, 22);
CALL sp_insert_pokemon_evolucao(37, 23);
CALL sp_insert_pokemon_evolucao(39, 24);
CALL sp_insert_pokemon_evolucao(41, 25);
CALL sp_insert_pokemon_evolucao(43, 26);
CALL sp_insert_pokemon_evolucao(44, 27);
CALL sp_insert_pokemon_evolucao(46, 28);
CALL sp_insert_pokemon_evolucao(48, 29);
CALL sp_insert_pokemon_evolucao(50, 30);
CALL sp_insert_pokemon_evolucao(52, 31);
CALL sp_insert_pokemon_evolucao(54, 32);
CALL sp_insert_pokemon_evolucao(56, 33);
CALL sp_insert_pokemon_evolucao(58, 34);
CALL sp_insert_pokemon_evolucao(60, 35);
CALL sp_insert_pokemon_evolucao(61, 36);
CALL sp_insert_pokemon_evolucao(63, 37);
CALL sp_insert_pokemon_evolucao(64, 38);
CALL sp_insert_pokemon_evolucao(66, 39);
CALL sp_insert_pokemon_evolucao(67, 40);
CALL sp_insert_pokemon_evolucao(69, 41);
CALL sp_insert_pokemon_evolucao(70, 42);
CALL sp_insert_pokemon_evolucao(72, 43);
CALL sp_insert_pokemon_evolucao(74, 44);
CALL sp_insert_pokemon_evolucao(75, 45);
CALL sp_insert_pokemon_evolucao(77, 46);
CALL sp_insert_pokemon_evolucao(79, 47);
CALL sp_insert_pokemon_evolucao(81, 48);
CALL sp_insert_pokemon_evolucao(84, 49);
CALL sp_insert_pokemon_evolucao(86, 50);
CALL sp_insert_pokemon_evolucao(88, 51);
CALL sp_insert_pokemon_evolucao(90, 52);
CALL sp_insert_pokemon_evolucao(92, 53);
CALL sp_insert_pokemon_evolucao(93, 54);
CALL sp_insert_pokemon_evolucao(96, 55);
CALL sp_insert_pokemon_evolucao(98, 56);
CALL sp_insert_pokemon_evolucao(100, 57);
CALL sp_insert_pokemon_evolucao(102, 58);
CALL sp_insert_pokemon_evolucao(104, 59);
CALL sp_insert_pokemon_evolucao(109, 60);
CALL sp_insert_pokemon_evolucao(111, 61);
CALL sp_insert_pokemon_evolucao(116, 62);
CALL sp_insert_pokemon_evolucao(118, 63);
CALL sp_insert_pokemon_evolucao(120, 64);
CALL sp_insert_pokemon_evolucao(129, 65);
CALL sp_insert_pokemon_evolucao(133, 66);
CALL sp_insert_pokemon_evolucao(133, 67);
CALL sp_insert_pokemon_evolucao(133, 68);
CALL sp_insert_pokemon_evolucao(138, 69);
CALL sp_insert_pokemon_evolucao(140, 70);
CALL sp_insert_pokemon_evolucao(147, 71);
CALL sp_insert_pokemon_evolucao(148, 72);

/*INSERTS HABILIDADE DOS POKEMONS*/
CALL sp_insert_pokemon_habilidade(1, 1);
CALL sp_insert_pokemon_habilidade(1, 2);
CALL sp_insert_pokemon_habilidade(2, 1);
CALL sp_insert_pokemon_habilidade(2, 2);
CALL sp_insert_pokemon_habilidade(3, 1);
CALL sp_insert_pokemon_habilidade(3, 2);
CALL sp_insert_pokemon_habilidade(4, 3);
CALL sp_insert_pokemon_habilidade(4, 4);
CALL sp_insert_pokemon_habilidade(5, 3);
CALL sp_insert_pokemon_habilidade(5, 4);
CALL sp_insert_pokemon_habilidade(6, 3);
CALL sp_insert_pokemon_habilidade(6, 4);
CALL sp_insert_pokemon_habilidade(7, 5);
CALL sp_insert_pokemon_habilidade(7, 6);
CALL sp_insert_pokemon_habilidade(8, 5);
CALL sp_insert_pokemon_habilidade(8, 6);
CALL sp_insert_pokemon_habilidade(9, 5);
CALL sp_insert_pokemon_habilidade(9, 6);
CALL sp_insert_pokemon_habilidade(10, 7);
CALL sp_insert_pokemon_habilidade(10, 8);
CALL sp_insert_pokemon_habilidade(11, 9);
CALL sp_insert_pokemon_habilidade(12, 10);
CALL sp_insert_pokemon_habilidade(12, 11);
CALL sp_insert_pokemon_habilidade(13, 7);
CALL sp_insert_pokemon_habilidade(13, 8);
CALL sp_insert_pokemon_habilidade(14, 9);
CALL sp_insert_pokemon_habilidade(15, 12);
CALL sp_insert_pokemon_habilidade(15, 13);
CALL sp_insert_pokemon_habilidade(16, 14);
CALL sp_insert_pokemon_habilidade(16, 15);
CALL sp_insert_pokemon_habilidade(16, 16);
CALL sp_insert_pokemon_habilidade(17, 14);
CALL sp_insert_pokemon_habilidade(17, 15);
CALL sp_insert_pokemon_habilidade(17, 16);
CALL sp_insert_pokemon_habilidade(18, 14);
CALL sp_insert_pokemon_habilidade(18, 15);
CALL sp_insert_pokemon_habilidade(18, 16);
CALL sp_insert_pokemon_habilidade(19, 8);
CALL sp_insert_pokemon_habilidade(19, 17);
CALL sp_insert_pokemon_habilidade(19, 18);
CALL sp_insert_pokemon_habilidade(20, 8);
CALL sp_insert_pokemon_habilidade(20, 17);
CALL sp_insert_pokemon_habilidade(20, 18);
CALL sp_insert_pokemon_habilidade(21, 14);
CALL sp_insert_pokemon_habilidade(21, 13);
CALL sp_insert_pokemon_habilidade(22, 14);
CALL sp_insert_pokemon_habilidade(22, 13);
CALL sp_insert_pokemon_habilidade(23, 19);
CALL sp_insert_pokemon_habilidade(23, 9);
CALL sp_insert_pokemon_habilidade(23, 20);
CALL sp_insert_pokemon_habilidade(24, 19);
CALL sp_insert_pokemon_habilidade(24, 9);
CALL sp_insert_pokemon_habilidade(24, 20);
CALL sp_insert_pokemon_habilidade(25, 21);
CALL sp_insert_pokemon_habilidade(25, 22);
CALL sp_insert_pokemon_habilidade(26, 21);
CALL sp_insert_pokemon_habilidade(26, 22);
CALL sp_insert_pokemon_habilidade(27, 23);
CALL sp_insert_pokemon_habilidade(27, 24);
CALL sp_insert_pokemon_habilidade(28, 23);
CALL sp_insert_pokemon_habilidade(28, 24);
CALL sp_insert_pokemon_habilidade(29, 25);
CALL sp_insert_pokemon_habilidade(29, 26);
CALL sp_insert_pokemon_habilidade(29, 18);
CALL sp_insert_pokemon_habilidade(30, 25);
CALL sp_insert_pokemon_habilidade(30, 26);
CALL sp_insert_pokemon_habilidade(30, 18);
CALL sp_insert_pokemon_habilidade(31, 25);
CALL sp_insert_pokemon_habilidade(31, 26);
CALL sp_insert_pokemon_habilidade(31, 27);
CALL sp_insert_pokemon_habilidade(32, 25);
CALL sp_insert_pokemon_habilidade(32, 26);
CALL sp_insert_pokemon_habilidade(32, 18);
CALL sp_insert_pokemon_habilidade(33, 25);
CALL sp_insert_pokemon_habilidade(33, 26);
CALL sp_insert_pokemon_habilidade(33, 18);
CALL sp_insert_pokemon_habilidade(34, 27);
CALL sp_insert_pokemon_habilidade(34, 25);
CALL sp_insert_pokemon_habilidade(34, 26);
CALL sp_insert_pokemon_habilidade(35, 28);
CALL sp_insert_pokemon_habilidade(35, 29);
CALL sp_insert_pokemon_habilidade(35, 30);
CALL sp_insert_pokemon_habilidade(36, 28);
CALL sp_insert_pokemon_habilidade(36, 29);
CALL sp_insert_pokemon_habilidade(36, 31);
CALL sp_insert_pokemon_habilidade(37, 32);
CALL sp_insert_pokemon_habilidade(37, 33);
CALL sp_insert_pokemon_habilidade(38, 32);
CALL sp_insert_pokemon_habilidade(38, 33);
CALL sp_insert_pokemon_habilidade(39, 28);
CALL sp_insert_pokemon_habilidade(39, 34);
CALL sp_insert_pokemon_habilidade(39, 30);
CALL sp_insert_pokemon_habilidade(40, 28);
CALL sp_insert_pokemon_habilidade(40, 34);
CALL sp_insert_pokemon_habilidade(40, 35);
CALL sp_insert_pokemon_habilidade(41, 36);
CALL sp_insert_pokemon_habilidade(41, 37);
CALL sp_insert_pokemon_habilidade(42, 36);
CALL sp_insert_pokemon_habilidade(42, 37);
CALL sp_insert_pokemon_habilidade(43, 2);
CALL sp_insert_pokemon_habilidade(43, 8);
CALL sp_insert_pokemon_habilidade(44, 2);
CALL sp_insert_pokemon_habilidade(44, 38);
CALL sp_insert_pokemon_habilidade(45, 2);
CALL sp_insert_pokemon_habilidade(45, 39);
CALL sp_insert_pokemon_habilidade(46, 39);
CALL sp_insert_pokemon_habilidade(46, 40);
CALL sp_insert_pokemon_habilidade(46, 41);
CALL sp_insert_pokemon_habilidade(47, 39);
CALL sp_insert_pokemon_habilidade(47, 40);
CALL sp_insert_pokemon_habilidade(47, 41);
CALL sp_insert_pokemon_habilidade(48, 10);
CALL sp_insert_pokemon_habilidade(48, 11);
CALL sp_insert_pokemon_habilidade(48, 8);
CALL sp_insert_pokemon_habilidade(49, 7);
CALL sp_insert_pokemon_habilidade(49, 11);
CALL sp_insert_pokemon_habilidade(49, 42);
CALL sp_insert_pokemon_habilidade(50, 23);
CALL sp_insert_pokemon_habilidade(50, 43);
CALL sp_insert_pokemon_habilidade(50, 44);
CALL sp_insert_pokemon_habilidade(51, 23);
CALL sp_insert_pokemon_habilidade(51, 43);
CALL sp_insert_pokemon_habilidade(51, 44);
CALL sp_insert_pokemon_habilidade(52, 45);
CALL sp_insert_pokemon_habilidade(52, 46);
CALL sp_insert_pokemon_habilidade(52, 20);
CALL sp_insert_pokemon_habilidade(53, 47);
CALL sp_insert_pokemon_habilidade(53, 46);
CALL sp_insert_pokemon_habilidade(53, 20);
CALL sp_insert_pokemon_habilidade(54, 41);
CALL sp_insert_pokemon_habilidade(54, 48);
CALL sp_insert_pokemon_habilidade(54, 49);
CALL sp_insert_pokemon_habilidade(55, 41);
CALL sp_insert_pokemon_habilidade(55, 48);
CALL sp_insert_pokemon_habilidade(55, 49);
CALL sp_insert_pokemon_habilidade(56, 50);
CALL sp_insert_pokemon_habilidade(56, 51);
CALL sp_insert_pokemon_habilidade(56, 52);
CALL sp_insert_pokemon_habilidade(57, 50);
CALL sp_insert_pokemon_habilidade(57, 51);
CALL sp_insert_pokemon_habilidade(57, 52);
CALL sp_insert_pokemon_habilidade(58, 19);
CALL sp_insert_pokemon_habilidade(58, 32);
CALL sp_insert_pokemon_habilidade(58, 53);
CALL sp_insert_pokemon_habilidade(59, 19);
CALL sp_insert_pokemon_habilidade(59, 32);
CALL sp_insert_pokemon_habilidade(59, 53);
CALL sp_insert_pokemon_habilidade(60, 54);
CALL sp_insert_pokemon_habilidade(60, 41);
CALL sp_insert_pokemon_habilidade(60, 49);
CALL sp_insert_pokemon_habilidade(61, 54);
CALL sp_insert_pokemon_habilidade(61, 41);
CALL sp_insert_pokemon_habilidade(61, 49);
CALL sp_insert_pokemon_habilidade(62, 54);
CALL sp_insert_pokemon_habilidade(62, 41);
CALL sp_insert_pokemon_habilidade(62, 49);
CALL sp_insert_pokemon_habilidade(63, 55);
CALL sp_insert_pokemon_habilidade(63, 36);
CALL sp_insert_pokemon_habilidade(63, 29);
CALL sp_insert_pokemon_habilidade(64, 55);
CALL sp_insert_pokemon_habilidade(64, 36);
CALL sp_insert_pokemon_habilidade(64, 29);
CALL sp_insert_pokemon_habilidade(65, 55);
CALL sp_insert_pokemon_habilidade(65, 36);
CALL sp_insert_pokemon_habilidade(65, 29);
CALL sp_insert_pokemon_habilidade(66, 17);
CALL sp_insert_pokemon_habilidade(66, 56);
CALL sp_insert_pokemon_habilidade(66, 57);
CALL sp_insert_pokemon_habilidade(67, 17);
CALL sp_insert_pokemon_habilidade(67, 56);
CALL sp_insert_pokemon_habilidade(67, 57);
CALL sp_insert_pokemon_habilidade(68, 17);
CALL sp_insert_pokemon_habilidade(68, 56);
CALL sp_insert_pokemon_habilidade(68, 57);
CALL sp_insert_pokemon_habilidade(69, 2);
CALL sp_insert_pokemon_habilidade(69, 58);
CALL sp_insert_pokemon_habilidade(70, 2);
CALL sp_insert_pokemon_habilidade(70, 58);
CALL sp_insert_pokemon_habilidade(71, 2);
CALL sp_insert_pokemon_habilidade(71, 58);
CALL sp_insert_pokemon_habilidade(72, 59);
CALL sp_insert_pokemon_habilidade(72, 60);
CALL sp_insert_pokemon_habilidade(72, 6);
CALL sp_insert_pokemon_habilidade(73, 59);
CALL sp_insert_pokemon_habilidade(73, 60);
CALL sp_insert_pokemon_habilidade(73, 6);
CALL sp_insert_pokemon_habilidade(74, 61);
CALL sp_insert_pokemon_habilidade(74, 62);
CALL sp_insert_pokemon_habilidade(74, 23);
CALL sp_insert_pokemon_habilidade(75, 61);
CALL sp_insert_pokemon_habilidade(75, 62);
CALL sp_insert_pokemon_habilidade(75, 23);
CALL sp_insert_pokemon_habilidade(76, 61);
CALL sp_insert_pokemon_habilidade(76, 62);
CALL sp_insert_pokemon_habilidade(76, 23);
CALL sp_insert_pokemon_habilidade(77, 8);
CALL sp_insert_pokemon_habilidade(77, 32);
CALL sp_insert_pokemon_habilidade(77, 63);
CALL sp_insert_pokemon_habilidade(78, 8);
CALL sp_insert_pokemon_habilidade(78, 32);
CALL sp_insert_pokemon_habilidade(78, 63);
CALL sp_insert_pokemon_habilidade(79, 64);
CALL sp_insert_pokemon_habilidade(79, 65);
CALL sp_insert_pokemon_habilidade(79, 66);
CALL sp_insert_pokemon_habilidade(80, 64);
CALL sp_insert_pokemon_habilidade(80, 65);
CALL sp_insert_pokemon_habilidade(80, 66);
CALL sp_insert_pokemon_habilidade(81, 67);
CALL sp_insert_pokemon_habilidade(81, 62);
CALL sp_insert_pokemon_habilidade(81, 68);
CALL sp_insert_pokemon_habilidade(82, 67);
CALL sp_insert_pokemon_habilidade(82, 62);
CALL sp_insert_pokemon_habilidade(82, 68);
CALL sp_insert_pokemon_habilidade(83, 14);
CALL sp_insert_pokemon_habilidade(83, 36);
CALL sp_insert_pokemon_habilidade(83, 52);
CALL sp_insert_pokemon_habilidade(84, 8);
CALL sp_insert_pokemon_habilidade(84, 69);
CALL sp_insert_pokemon_habilidade(84, 15);
CALL sp_insert_pokemon_habilidade(85, 8);
CALL sp_insert_pokemon_habilidade(85, 69);
CALL sp_insert_pokemon_habilidade(85, 15);
CALL sp_insert_pokemon_habilidade(86, 70);
CALL sp_insert_pokemon_habilidade(86, 71);
CALL sp_insert_pokemon_habilidade(86, 72);
CALL sp_insert_pokemon_habilidade(87, 70);
CALL sp_insert_pokemon_habilidade(87, 71);
CALL sp_insert_pokemon_habilidade(87, 72);
CALL sp_insert_pokemon_habilidade(88, 38);
CALL sp_insert_pokemon_habilidade(88, 73);
CALL sp_insert_pokemon_habilidade(88, 74);
CALL sp_insert_pokemon_habilidade(89, 38);
CALL sp_insert_pokemon_habilidade(89, 73);
CALL sp_insert_pokemon_habilidade(89, 74);
CALL sp_insert_pokemon_habilidade(90, 75);
CALL sp_insert_pokemon_habilidade(90, 76);
CALL sp_insert_pokemon_habilidade(90, 77);
CALL sp_insert_pokemon_habilidade(91, 75);
CALL sp_insert_pokemon_habilidade(91, 76);
CALL sp_insert_pokemon_habilidade(91, 77);
CALL sp_insert_pokemon_habilidade(92, 78);
CALL sp_insert_pokemon_habilidade(93, 78);
CALL sp_insert_pokemon_habilidade(94, 79);
CALL sp_insert_pokemon_habilidade(95, 61);
CALL sp_insert_pokemon_habilidade(95, 62);
CALL sp_insert_pokemon_habilidade(95, 80);
CALL sp_insert_pokemon_habilidade(96, 81);
CALL sp_insert_pokemon_habilidade(96, 82);
CALL sp_insert_pokemon_habilidade(96, 36);
CALL sp_insert_pokemon_habilidade(97, 81);
CALL sp_insert_pokemon_habilidade(97, 82);
CALL sp_insert_pokemon_habilidade(97, 36);
CALL sp_insert_pokemon_habilidade(98, 83);
CALL sp_insert_pokemon_habilidade(98, 75);
CALL sp_insert_pokemon_habilidade(98, 27);
CALL sp_insert_pokemon_habilidade(99, 83);
CALL sp_insert_pokemon_habilidade(99, 75);
CALL sp_insert_pokemon_habilidade(99, 27);
CALL sp_insert_pokemon_habilidade(100, 84);
CALL sp_insert_pokemon_habilidade(100, 21);
CALL sp_insert_pokemon_habilidade(100, 85);
CALL sp_insert_pokemon_habilidade(101, 84);
CALL sp_insert_pokemon_habilidade(101, 21);
CALL sp_insert_pokemon_habilidade(101, 85);
CALL sp_insert_pokemon_habilidade(102, 2);
CALL sp_insert_pokemon_habilidade(102, 86);
CALL sp_insert_pokemon_habilidade(103, 2);
CALL sp_insert_pokemon_habilidade(103, 86);
CALL sp_insert_pokemon_habilidade(104, 61);
CALL sp_insert_pokemon_habilidade(104, 22);
CALL sp_insert_pokemon_habilidade(104, 87);
CALL sp_insert_pokemon_habilidade(105, 61);
CALL sp_insert_pokemon_habilidade(105, 22);
CALL sp_insert_pokemon_habilidade(105, 87);
CALL sp_insert_pokemon_habilidade(106, 47);
CALL sp_insert_pokemon_habilidade(106, 88);
CALL sp_insert_pokemon_habilidade(106, 89);
CALL sp_insert_pokemon_habilidade(107, 14);
CALL sp_insert_pokemon_habilidade(107, 90);
CALL sp_insert_pokemon_habilidade(107, 36);
CALL sp_insert_pokemon_habilidade(108, 65);
CALL sp_insert_pokemon_habilidade(108, 64);
CALL sp_insert_pokemon_habilidade(108, 48);
CALL sp_insert_pokemon_habilidade(109, 78);
CALL sp_insert_pokemon_habilidade(109, 91);
CALL sp_insert_pokemon_habilidade(109, 38);
CALL sp_insert_pokemon_habilidade(110, 78);
CALL sp_insert_pokemon_habilidade(110, 91);
CALL sp_insert_pokemon_habilidade(110, 38);
CALL sp_insert_pokemon_habilidade(111, 22);
CALL sp_insert_pokemon_habilidade(111, 61);
CALL sp_insert_pokemon_habilidade(111, 88);
CALL sp_insert_pokemon_habilidade(112, 22);
CALL sp_insert_pokemon_habilidade(112, 61);
CALL sp_insert_pokemon_habilidade(112, 88);
CALL sp_insert_pokemon_habilidade(113, 95);
CALL sp_insert_pokemon_habilidade(113, 92);
CALL sp_insert_pokemon_habilidade(113, 94);
CALL sp_insert_pokemon_habilidade(114, 2);
CALL sp_insert_pokemon_habilidade(114, 95);
CALL sp_insert_pokemon_habilidade(114, 66);
CALL sp_insert_pokemon_habilidade(115, 69);
CALL sp_insert_pokemon_habilidade(115, 96);
CALL sp_insert_pokemon_habilidade(115, 36);
CALL sp_insert_pokemon_habilidade(116, 49);
CALL sp_insert_pokemon_habilidade(116, 13);
CALL sp_insert_pokemon_habilidade(116, 41);
CALL sp_insert_pokemon_habilidade(117, 25);
CALL sp_insert_pokemon_habilidade(117, 13);
CALL sp_insert_pokemon_habilidade(117, 41);
CALL sp_insert_pokemon_habilidade(118, 49);
CALL sp_insert_pokemon_habilidade(118, 97);
CALL sp_insert_pokemon_habilidade(118, 22);
CALL sp_insert_pokemon_habilidade(119, 49);
CALL sp_insert_pokemon_habilidade(119, 97);
CALL sp_insert_pokemon_habilidade(119, 22);
CALL sp_insert_pokemon_habilidade(120, 98);
CALL sp_insert_pokemon_habilidade(120, 92);
CALL sp_insert_pokemon_habilidade(120, 68);
CALL sp_insert_pokemon_habilidade(121, 98);
CALL sp_insert_pokemon_habilidade(121, 92);
CALL sp_insert_pokemon_habilidade(121, 68);
CALL sp_insert_pokemon_habilidade(122, 84);
CALL sp_insert_pokemon_habilidade(122, 99);
CALL sp_insert_pokemon_habilidade(122, 46);
CALL sp_insert_pokemon_habilidade(123, 12);
CALL sp_insert_pokemon_habilidade(123, 46);
CALL sp_insert_pokemon_habilidade(123, 57);
CALL sp_insert_pokemon_habilidade(124, 64);
CALL sp_insert_pokemon_habilidade(124, 82);
CALL sp_insert_pokemon_habilidade(124, 40);
CALL sp_insert_pokemon_habilidade(125, 21);
CALL sp_insert_pokemon_habilidade(125, 50);
CALL sp_insert_pokemon_habilidade(126, 63);
CALL sp_insert_pokemon_habilidade(126, 50);
CALL sp_insert_pokemon_habilidade(127, 83);
CALL sp_insert_pokemon_habilidade(127, 100);
CALL sp_insert_pokemon_habilidade(127, 101);
CALL sp_insert_pokemon_habilidade(128, 19);
CALL sp_insert_pokemon_habilidade(128, 51);
CALL sp_insert_pokemon_habilidade(128, 27);
CALL sp_insert_pokemon_habilidade(129, 49);
CALL sp_insert_pokemon_habilidade(129, 102);
CALL sp_insert_pokemon_habilidade(130, 19);
CALL sp_insert_pokemon_habilidade(130, 101);
CALL sp_insert_pokemon_habilidade(131, 54);
CALL sp_insert_pokemon_habilidade(131, 75);
CALL sp_insert_pokemon_habilidade(131, 71);
CALL sp_insert_pokemon_habilidade(132, 47);
CALL sp_insert_pokemon_habilidade(132, 103);
CALL sp_insert_pokemon_habilidade(133, 8);
CALL sp_insert_pokemon_habilidade(133, 104);
CALL sp_insert_pokemon_habilidade(133, 105);
CALL sp_insert_pokemon_habilidade(134, 54);
CALL sp_insert_pokemon_habilidade(134, 71);
CALL sp_insert_pokemon_habilidade(135, 106);
CALL sp_insert_pokemon_habilidade(135, 107);
CALL sp_insert_pokemon_habilidade(136, 32);
CALL sp_insert_pokemon_habilidade(136, 17);
CALL sp_insert_pokemon_habilidade(137, 108);
CALL sp_insert_pokemon_habilidade(137, 109);
CALL sp_insert_pokemon_habilidade(137, 68);
CALL sp_insert_pokemon_habilidade(138, 49);
CALL sp_insert_pokemon_habilidade(138, 75);
CALL sp_insert_pokemon_habilidade(138, 80);
CALL sp_insert_pokemon_habilidade(139, 49);
CALL sp_insert_pokemon_habilidade(139, 75);
CALL sp_insert_pokemon_habilidade(139, 80);
CALL sp_insert_pokemon_habilidade(140, 49);
CALL sp_insert_pokemon_habilidade(140, 87);
CALL sp_insert_pokemon_habilidade(140, 80);
CALL sp_insert_pokemon_habilidade(141, 49);
CALL sp_insert_pokemon_habilidade(141, 87);
CALL sp_insert_pokemon_habilidade(141, 80);
CALL sp_insert_pokemon_habilidade(142, 61);
CALL sp_insert_pokemon_habilidade(142, 110);
CALL sp_insert_pokemon_habilidade(142, 20);
CALL sp_insert_pokemon_habilidade(143, 111);
CALL sp_insert_pokemon_habilidade(143, 70);
CALL sp_insert_pokemon_habilidade(143, 58);
CALL sp_insert_pokemon_habilidade(144, 110);
CALL sp_insert_pokemon_habilidade(144, 112);
CALL sp_insert_pokemon_habilidade(145, 110);
CALL sp_insert_pokemon_habilidade(145, 21);
CALL sp_insert_pokemon_habilidade(146, 110);
CALL sp_insert_pokemon_habilidade(146, 63);
CALL sp_insert_pokemon_habilidade(147, 9);
CALL sp_insert_pokemon_habilidade(147, 113);
CALL sp_insert_pokemon_habilidade(148, 9);
CALL sp_insert_pokemon_habilidade(148, 113);
CALL sp_insert_pokemon_habilidade(149, 36);
CALL sp_insert_pokemon_habilidade(149, 114);
CALL sp_insert_pokemon_habilidade(150, 110);
CALL sp_insert_pokemon_habilidade(150, 20);
CALL sp_insert_pokemon_habilidade(151, 55);

###############################################################################
/*SELECTS PARA TESTAR OS CÓDIGOS*/
/*SELECT DO POKEMON COM SUAS FRAQUEZAS*/
SELECT 
    p.id AS id_pokemon,
    p.nome AS nome_pokemon,
    GROUP_CONCAT(f.nome SEPARATOR ', ') AS fraquezas_pokemon
FROM 
    tb_pokemon p
JOIN 
    tb_pokemon_fraqueza pf ON p.id = pf.id_pokemon
JOIN 
    tb_fraqueza f ON pf.id_fraqueza = f.id
GROUP BY 
    p.id;

 ####################################################################
 /*SELECT DOS POKEMONS COM SUAS HABILIDADES*/
SELECT 
    p.id AS numero_pokedex,
    p.nome AS nome,
    GROUP_CONCAT(h.nome SEPARATOR ' ou ') AS habilidades
FROM 
    tb_pokemon p
JOIN 
    tb_pokemon_habilidade ph ON p.id = ph.id_pokemon
JOIN 
    tb_habilidade h ON ph.id_habilidade = h.id
GROUP BY 
    p.id, p.nome;
#######################################################################

#############################################################################
/*SELECT DOS POKEMONS COM SEUS TIPOS*/
SELECT 
	p.id AS numero_dex,
    p.nome AS nome_pokemon,
    GROUP_CONCAT(t.nome SEPARATOR ', ') AS tipo_do_pokemon
FROM 
    tb_pokemon p
JOIN 
    tb_pokemon_tipo pt ON p.id = pt.id_pokemon
JOIN 
    tb_tipo t ON pt.id_tipo = t.id
GROUP BY 
    p.id;
#########################################################################
/*SELECT DOS POKEMONS COM SUAS EVOLUÇÕES*/
SELECT 
    p.id AS numero_pokedex,
    p.nome AS nome,
    e.nome AS evolução
FROM 
    tb_pokemon p
JOIN 
    tb_pokemon_evolucao pe ON p.id = pe.id_pokemon
JOIN 
    tb_evolucao e ON pe.id_evolucao = e.id;

##################################################################
/*SELECT DOS POKEMONS COM SEU TIPO, HABILIDADE, DESC HABILIDADE*/
SELECT 
    p.id AS numero_pokedex,
    p.nome AS nome_pokemon,
    GROUP_CONCAT(DISTINCT t.nome ORDER BY t.nome ASC SEPARATOR ' ou ') AS tipo,
    h.nome AS habilidade,
    h.descricao AS descricao_habilidade
FROM 
    tb_pokemon p
JOIN 
    tb_pokemon_tipo pt ON p.id = pt.id_pokemon
JOIN 
    tb_tipo t ON pt.id_tipo = t.id
JOIN 
    tb_pokemon_habilidade ph ON p.id = ph.id_pokemon
JOIN 
    tb_habilidade h ON ph.id_habilidade = h.id
GROUP BY 
    p.id, p.nome, h.nome, h.descricao
ORDER BY 
    p.id;
###################################################################
/*SELECT DOS POKEMONS COM SUA DESC E SEU TIPO*/
SELECT 
    p.id AS numero_pokemon,
    p.nome AS nome_pokemon,
    p.descricao AS descricao_pokemon,
    GROUP_CONCAT(t.nome SEPARATOR ', ') AS tipo_do_pokemon
FROM 
    tb_pokemon p
JOIN 
    tb_pokemon_tipo pt ON p.id = pt.id_pokemon
JOIN 
    tb_tipo t ON pt.id_tipo = t.id
GROUP BY 
    p.id;

###########################################################################
/*SELECT DAS TABELAS COM OS DADOS PARA FAZER O LINK DAS CHAVES*/
SELECT * FROM tb_pokemon_evolucao;
SELECT * FROM tb_pokemon_tipo;
SELECT * FROM tb_tipo;
SELECT * FROM tb_pokemon;
SELECT * FROM tb_fraqueza;
SELECT * FROM tb_evolucao;